### ISSUE TITLE
Prevent re-scraping already fetched tweets with since_id

### ISSUE THREAD

**Issue by triatic** [trevorhobenshield/twitter-api-client#100]
On Twitter API v2, the parameter `since_id` was very useful in preventing fetching tweets which were already fetched.

Can twitter-api-client be made to store and reuse `since_id` for consecutive, identical queries, to massively reduce the tweet consumption?

**Comment by trevorhobenshield** [comment]
This currently falls out of scope for this package as it requires some form of post-processing to achieve the result, as there is no public/free endpoint defined for this operation. Generally, the goal of this package is only to provide a simple low-level interface to the free endpoints. 

If there is a large demand for this I may reconsider looking into it in the future.
