### ISSUE TITLE
about ct0

### ISSUE THREAD

**Issue by wxtsky** [trevorhobenshield/twitter-api-client#102]
Hello, I have discovered how to only use auth_token performs a series of operations instead of using ct0, I have already succeeded!

**Comment by wxtsky** [comment]
and also，i hope you can add proxy function.

**Comment by trevorhobenshield** [comment]
> Hello, I have discovered how to only use auth_token performs a series of operations instead of using ct0, I have already succeeded!

If you can provide an example that would be interesting. You shouldn't be able to.

E.g.

```json
{"errors": [{"code": 353, "message": "This request requires a matching csrf cookie and header."}]}
```

**Comment by witherBattler** [comment]
Hey, @wxtsky , could you please share how you managed to only use auth_token without ct0 for scraping?

**Comment by amanzrx4** [comment]
@trevorhobenshield @witherBattler 
I'm exclusively working on crawling twitter for a while.
`auth_token` is all you need in twitter
for `ct0` just hit twitter root url with auth_token cookie and you'll get the ct0 in set-cookie header

**Comment by owenkrause** [comment]
I checked one of his repos and he figured out how to generate the ct0 token from a random seed and it works with any auth_token. so technically, yes, since ct0 generation is arbitrary, you can just use auth_token.

**Comment by winer328** [comment]
> Hello, I have discovered how to only use auth_token performs a series of operations instead of using ct0, I have already succeeded!

How did you implement it?
I tried several times but faild all the times with 401 - authentication error.

**Comment by amanzrx4** [comment]
@winer328 `ct0` is a short lived cookie, you can regenerate it as long as you've the long lived `auth_token`. `auth_token` is all you need to scrap everything twitter(x). 
**Hint:** Render twitter in a browser (sandbox) and run requests from browser console, the browser will take care of the cookies & headers.

**Comment by owenkrause** [comment]
> > Hello, I have discovered how to only use auth_token performs a series of operations instead of using ct0, I have already succeeded!
> 
> How did you implement it? I tried several times but faild all the times with 401 - authentication error.

I open sourced a twitter client, haven't updated it in a while but the logic should should still work. 

https://github.com/owenkrause/twitter-monitor-public/blob/main/twitter/login.go#L84

**Comment by winer328** [comment]
> > > Hello, I have discovered how to only use auth_token performs a series of operations instead of using ct0, I have already succeeded!
> > 
> > 
> > How did you implement it? I tried several times but faild all the times with 401 - authentication error.
> 
> I open sourced a twitter client, haven't updated it in a while but the logic should should still work.
> 
> https://github.com/owenkrause/twitter-monitor-public/blob/main/twitter/login.go#L84

Thanks very much.

**Comment by oymonday29-droid** [comment]
login: mnfgfd12345 
password: dAhvlHzPPF 
phone: +966567390855 
ct0: d4cc49e8304e3ca20a53dbd5f8ad32bde43b87a4283123677e995478825da4d802d7e78bc7aed46690fd121545dc2c12f73f1a84f8e36dc472d208cd9b1e7a5b1b90158b71603ec41655dd2374a1562d 
auth_token: 9af593b4ca1d63705dbd517a8449604310e7ed26
