### ISSUE TITLE
Login failed still returns client

### ISSUE THREAD

**Issue by ramicaza** [trevorhobenshield/twitter-api-client#106]
When the login flow fails, the scraper logs the error but keeps on chugging like nothing happened. There should probably be an exception raised or somehow indicate the failure to the caller of the constructors Search() or Scrape()

<img width="688" alt="Screen Shot 2023-07-05 at 2 35 27 PM" src="https://github.com/trevorhobenshield/twitter-api-client/assets/8342756/88ec4da1-e363-4c69-af9f-085842dd975d">

**Comment by trevorhobenshield** [comment]
Initially this was done on purpose, basically allowing a guest session to be used as a fallback with limited endpoints. Now, due to the recent changes as of July 1 this is irrelevant, so I agree this should be modified to throw an exception rather than return a guest session.
