### ISSUE TITLE
email confirmation code challenge

### ISSUE THREAD

**Issue by Troais** [trevorhobenshield/twitter-api-client#107]
Yesterday it was working without any issues, but today when I try to log in, it asks for verification for any account, regardless of which account it is. Is there a way to fix this? Will it ask for verification every time I log in?

**Comment by trevorhobenshield** [comment]
Could be your IP, I have noticed some addresses from common VPNs are flagged intermittently, and there is no way of knowing when certain ones will be affected. Twitter also may be tightening things up, so we'll have to see what happens over time.
