### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by ducan-ne** [trevorhobenshield/twitter-api-client#12]
Hi, I hadn't used this before, but I wonder if these APIs have a small rate limit?

**Comment by trevorhobenshield** [comment]
yep, 500/15 mins for most, some are as low as 50/15 mins. Also see: https://developer.twitter.com/en/docs/twitter-api/rate-limits

**Comment by mangaroo** [comment]
Would the per app or per user apply in this case?

**Comment by trevorhobenshield** [comment]
@mangaroo Good question. The docs I pointed to above were meant to be more of a supplementary resource, just to illustrate the general shape of their newest API. Scraping data mostly relies on the "undocumented" GraphQL API endpoints. Account operations generally use v1 endpoints, and a few account operations + search use the new v2 endpoints.

Overall most scraping/search operations hover around 500 reqs/15 mins, and Account operations range between 10-500 reqs/15 mins.

**Comment by mangaroo** [comment]
Thank you again, and for this, best wishes.
