### ISSUE TITLE
Tweets not being returned in Search

### ISSUE THREAD

**Issue by Abolfazl** [trevorhobenshield/twitter-api-client#121]
Recently I have found that tweets are not being properly returned in search:

My code is:

    search = Search(EMAIL, USERNAME, PASSWORD, save=True, debug=1)
    last_hour = int(time()) - 3600
    search.run(queries=[{'category': 'Latest','query': f'(wn.nr OR gleam.io) since_time:{last_hour}'}], limit=100, latest=True) # Return all tweets made in last hour that are from 1 of 2 domains

This returns: `[success] Returned 0 search results for (wn.nr OR gleam.io) since_time:1690391462`

But when I manually copy this search into Twitter search, it actually returns the tweets. How come there are no tweets being received from `twitter-api-client`?

**Comment by Abolfazl** [comment]
I just checked and it looks like the advanced search is using the `SearchTimeline` endpoint in the standard `x OR y` format.

I guess it's back to normal?

**Comment by msvprogs** [comment]
Yes, it seems so. I also confirmed that search behavior has returned back to normal.
