### ISSUE TITLE
Get latest tweet from users using scraper.tweets in reverse chronological order with guest session

### ISSUE THREAD

**Issue by woncoh1** [trevorhobenshield/twitter-api-client#127]
Hi,

- I was wondering whether [`scraper.tweets(['rest_id1', 'rest_id2', ....])`](https://github.com/trevorhobenshield/twitter-api-client/blob/586a337ee5e8f6bd3902f04b983ad5422a6364c6/twitter/scraper.py#L74) without authentication (login with username and password, cookies, or previous logged in session) can sort the latest tweets in reverse chronological order (latest first).

- `scraper.tweets` with a guest session seems to sample tweets based on likes or some other metric.

- Is there a query or keyword argument that I can pass to `scraper.tweets` to get the results sorted reverse chronologically so that I can get the latest tweets with out logging in?

Thanks for such as amazing application.

**Comment by woncoh1** [comment]
Solved this using some custom code.

**Comment by guotie** [comment]
how did you solve this problem?
