### ISSUE TITLE
Home timeline access

### ISSUE THREAD

**Issue by mef** [trevorhobenshield/twitter-api-client#13]
Hi,

I've read through the README file and examples directory, but could not find a way to get the tweets from home timeline in (reverse chronological order).

Is there a way to get these tweets (only the ones from people I am following, not the ones recommended "fo you" by twitter).

**Comment by trevorhobenshield** [comment]
> I've read through the README file and examples directory, but could not find a way to get the tweets from home timeline in (reverse chronological order).

Thanks! Nice catch, just added the home/latest timeline endpoints.

> Is there a way to get these tweets (only the ones from people I am following, not the ones recommended "fo you" by twitter).

Good question. It may be possible, I briefly tried to do this by setting/unsetting certain feature flags but didn't have much luck. The easy workaround would be to pull all your following IDs, pull your timeline, filter all timeline tweets which do not have and ID in your follow IDs set, then finally sort in reverse chronological order.

**Comment by mef** [comment]
Thanks!

I've had a quick look at the requests sent from the web client, and figured out that:

* `HomeTimeline` corresponds to the `For you` feed, whereas  
* `HomeLatestTimeline` corresponds to the `Following` feed (in reverse chronological order).

So all good, no extra filtering needed using this second endpoint.
