### ISSUE TITLE
ImportError: cannot import name 'member' from 'enum' (/usr/lib/python3.8/enum.py)

### ISSUE THREAD

**Issue by rui** [trevorhobenshield/twitter-api-client#131]
How to fix this error?

**Comment by czy19** [comment]
I have this problem too

**Comment by trevorhobenshield** [comment]
You'll need to upgrade to python 3.10 or greater.

https://github.com/trevorhobenshield/twitter-api-client/blob/586a337ee5e8f6bd3902f04b983ad5422a6364c6/setup.py#L451
