### ISSUE TITLE
What is the flow for solve the arkose captcha?

### ISSUE THREAD

**Issue by areyouokaydontworryimhere** [trevorhobenshield/twitter-api-client#148]
Hi, some time it show that we need to solve the arkose captcha. Is there anyway to solve it?

**Comment by imhuy** [comment]
1stcaptcha

**Comment by xuancuong1609** [comment]
> 1stcaptcha

Yes I know that. I mean how to solve it with API.

**Comment by trevorhobenshield** [comment]
@areyouokaydontworryimhere If you figure out how to do that without using a paid service feel free to let me know, that would be very interesting.
