### ISSUE TITLE
Entries have hidden hard limit separate from returned results

### ISSUE THREAD

**Issue by Survivian** [trevorhobenshield/twitter-api-client#149]
When using either `scraping.tweets` or `scraping.media`, the debug printer shows that there are hundreds or sometimes thousands of unique results when searching through with the cursor yet when it puts these results into the list for the entries it caps out at either 102 or 101 entries.
![entries](https://github.com/trevorhobenshield/twitter-api-client/assets/32820657/b5a38233-1474-4c3d-9080-c018d2bd2217)
In the above screenshot, I am running the `scraping.media` function with `debug=1` enabled.
As the cursor goes through the account it finds ~700 unique results (which lines up with the ~700 images/videos this user has uploaded) and stops there.
The `101` at the bottom is the number of actual entries the function fetches which is nowhere near the ~700 purported.
This number was obtained by this method:
```py
user_media = scraping.media([twitter_id_string])
print(len(user_media[0]['data']['user']['result']['timeline_v2']['timeline']['instructions'][0]['entries']))
```
Why is the number of entries in this list incongruous with the results that the API reports when scrolling through the user's feed?
Is there a separate way I should be gathering those entries that gets everything?
Any info would be appreciated.

**Comment by trevorhobenshield** [comment]
`user_media[0]` is only indexing into the first batch.

Each endpoint has a limit to the number of results it can return, usually between ~20 and ~100. 

Following your method, to get all media you would do:

```python

[y for x in user_media for y in x['data']['user']['result']['timeline_v2']['timeline']['instructions'][0]['entries']]

```

or simply:

```python
from twitter.util import find_key
import pandas as pd

df = pd.DataFrame(y for x in find_key(user_media, 'entries') for y in x)
df
```
