### ISSUE TITLE
Can't get tweet detail due to requi header

### ISSUE THREAD

**Issue by smilehun** [trevorhobenshield/twitter-api-client#151]
Hi admin, pls check again this funtion. I can't get anything 
tweets_by_ids = scraper.tweets_by_id([987, 876, 754])
tweets_details = scraper.tweets_details([987, 876, 754])

**Comment by Mitrajit** [comment]
@trevorhobenshield We are facing the same issue can you please solve this.

**Comment by trevorhobenshield** [comment]
Both are working on my end. You'll have to be careful not to exceed the rate limits, some endpoints are 50 requests/15 mins, others are 500 requests/15 mins. You can set `debug=1` to see your current state.

![a](https://github.com/trevorhobenshield/twitter-api-client/assets/59624054/e36cf859-0a41-4771-91c4-8d529232d4df)
