### ISSUE TITLE
Home timeline latest (following) uses home timeline (for you) endpoint

### ISSUE THREAD

**Issue by robindz** [trevorhobenshield/twitter-api-client#16]
https://github.com/trevorhobenshield/twitter-api-client/blob/eb902b6941c17fd6d61fcb0546b2e593d972245d/twitter/account.py#L352

This should be changed to `HomeLatestTimeline` instead of `HomeTimeline`.

**Comment by trevorhobenshield** [comment]
Nice catch, thanks!
