### ISSUE TITLE
user tweets pagination question

### ISSUE THREAD

**Issue by cop-discord** [trevorhobenshield/twitter-api-client#160]
is there any way to only get the last page of user tweets aka the latest tweets from the user

**Comment by trevorhobenshield** [comment]
A "page" isn't defined in Twitter, but they do have default "windows" (or whatever web-devs would call it) of 20-100 entries returned per request. So you'll have to specify a number.

So you would do something like:
```python
scraper.tweets([123456], limit=20, count=20)
```
Which would more closely mimic the behavior of the requests made in the web interface.
