### ISSUE TITLE
UserTweetsAndReplies endpoint got 404 status code

### ISSUE THREAD

**Issue by malone6** [trevorhobenshield/twitter-api-client#161]
The following error occurred when I was using `scraper.tweets_and_replies([user_id])`.
``` self.logger.error('Failed to get initial pagination data', e)
Message: 'Failed to get initial pagination data'
Arguments: (JSONDecodeError('Expecting value: line 1 column 1 (char 0)'),)
UserTweetsAndReplies: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
```
At the same time, other APIs such as `scraper.tweets` were working. 
Through my debugging, I discovered that a request encountered a 404 error
![image](https://github.com/trevorhobenshield/twitter-api-client/assets/15245112/8bb836d7-7c6c-4d14-8e3a-239438802091)

**Comment by trevorhobenshield** [comment]
Thanks for noting this. It doesn't look like others have experienced this so I'll have to close.
