### ISSUE TITLE
Unstable user/password and using cookies

### ISSUE THREAD

**Issue by reagle** [trevorhobenshield/twitter-api-client#164]
Hello, my tweets were failing for some reason and I came to this page and saw the warning in the README. Keeping up with twitter must be frustrating, so thank you for keeping this library going.

I was able to grab my cookie from my logged in Chrome browser (via Developer_Panel/Application/Cookie) and wonder if there's a way to do this programmatically -- instead of me copying and pasting when I cookie expires?

**Comment by trevorhobenshield** [comment]
Good question, there isn't a clean way to do this programmatically. There are naive ways to do it, but they are not robust enough, so I can't justify adding them.

Twitter was an odd exception in the first place, most large social media companies employ pretty good security measures to avoid programmatic logins. [instagrapi](https://github.com/subzeroid/instagrapi) and [TikTok-X-Argus](https://github.com/xtekky/TIkTok-X-Argus) are great examples of more "real" reverse engineering that is required to generate cookies and other special values. I would essentially have to do something along these lines, which takes time, and is very tedious. If I do figure out how to ensure a robust login-flow I will make the required changes.
