### ISSUE TITLE
Support For i/timeline

### ISSUE THREAD

**Issue by BrokedTV** [trevorhobenshield/twitter-api-client#165]
It would be great to have support for

https://twitter.com/i/timeline

which is the timeline that only show tweets where you have the bell notification on.

**Comment by trevorhobenshield** [comment]
This is probably an old v1 endpoint which was transitioned to the `HomeTimeline` GQL endpoint. What you're looking for is likely one of these:
```python
account.notifications()
account.home_timeline()
account.home_latest_timeline()
```
