### ISSUE TITLE
scraper.favoriters returns a cursor and will loop `DUP_LIMIT` (3) times for no reasons

### ISSUE THREAD

**Issue by JulienMaille** [trevorhobenshield/twitter-api-client#166]
https://github.com/trevorhobenshield/twitter-api-client/blob/5b29f5fe59c82cb85c7a7001afc9d8807f0281d3/twitter/scraper.py#L634-L645

Try to list favoriters for a tweet with ~5 tweets and it will _paginate even if not needed.
The returned cursor will be the same each time, and the json will not contain any data

```json
{
  'data': {
    'favoriters_timeline': {
      'timeline': {
        'instructions': [
          {
            'type': 'TimelineAddEntries',
            'entries': [
              {
                'entryId': 'cursor-top-YYYYYYYYYYYYYYYYYYYYYY',
                'sortIndex': 'YYYYYYYYYYYYYYYYYYYYYY',
                'content': {
                  'entryType': 'TimelineTimelineCursor',
                  '__typename': 'TimelineTimelineCursor',
                  'value': 'AAAAAAAAAAAAAAAAA==',
                  'cursorType': 'Top'
                }
              },
              {
                'entryId': 'cursor-bottom-XXXXXXXXXXXXXXXXXXX',
                'sortIndex': 'XXXXXXXXXXXXXXXXXXX',
                'content': {
                  'e ntryType': 'TimelineTimelineCursor',
                  '__typename': 'TimelineTimelineCursor',
                  'value': 'BBBBBBBBBBBBBBBBBBB==',
                  'cursorType': 'Bottom',
                  'stopOnEmptyResponse': True
                }
              }
            ]
          },
          {
            'type': 'TimelineTerminateTimeline',
            'direction': 'Bottom'
          }
        ],
        'responseObjects': {
          'feedbackActions': [
            
          ],
          'immediateReactions': [
            
          ]
        }
      }
    }
  }
}
```

**Comment by trevorhobenshield** [comment]
I can't seem to replicate this issue. It's likely due to expired cookies or some weird stuff going on in Twitter's backend.

As for the calls to _paginate, this was a design decision to keep things simple while adding robustness. Twitter response data is volatile and sometimes you have to go past the supposed "last cursor" in order to get more results. I use an arbitrary value of 2 or 3 additional requests to ensure there isn't more data left.

**Comment by JulienMaille** [comment]
@trevorhobenshield Thanks for looking into this. I tried with a fresh cookie and get the issue every time, that's weird.
If you add a trace like this: https://github.com/trevorhobenshield/twitter-api-client/compare/main...cihantas:twitter-api-client:main
Don't you get the trace 3 times whatever amount of favoriters is found?
