### ISSUE TITLE
Character limit on premium account

### ISSUE THREAD

**Issue by david-lev** [trevorhobenshield/twitter-api-client#167]
Hi, First thanks for your great library! 
I built a program for a client with a premium Twitter account (which allows you to exceed the character limit on a tweet, among other things), and indeed when I manually tweeting, I am allowed to exceed the limit, but through the library, when I tweet I get the following error: `Tweet needs to be a bit shorter. (186)`.
Is that a local limit or an error from the internal api the library is using?

**Comment by david-lev** [comment]
Anybody? please

**Comment by trevorhobenshield** [comment]
Thanks for the question David. Unfortunately I'm not planning on supporting premium API related features as I'm trying to keep everything free/open.
