### ISSUE TITLE
Make logging a toggle

### ISSUE THREAD

**Issue by robindz** [trevorhobenshield/twitter-api-client#17]
Currently logging is enabled by default and there is no way to turn this off (as far as I can tell).
It'd be appreciated if logging could be toggled on and/or off at runtime by calling a method or setting a variable.

Use case: some other programs might want to use the STDOUT output of a python script that uses this package, but it's currently full of debug/log messages, which result in a lot of extra/unnecessary parsing.

**Comment by trevorhobenshield** [comment]
Good point, have just added this in. You can now pass a debug level into `Account` and `Scraper` objects
