### ISSUE TITLE
Timeline function removed?

### ISSUE THREAD

**Issue by JackCrispy** [trevorhobenshield/twitter-api-client#173]
Hi, trying to fetch the timeline with
```python
scraper.home_latest_timeline()
```
and i get
```
AttributeError: 'Scraper' object has no attribute 'home_latest_timeline'
```

was timeline removed? How am I able to get timeline. Thanks

**Comment by JackCrispy** [comment]
Hey @trevorhobenshield, would you have any idea here?

**Comment by JulienMaille** [comment]
This is a function of `Account` not `Scraper`, have a look at the readme

**Comment by JackCrispy** [comment]
> This is a function of `Account` not `Scraper`, have a look at the readme

![image](https://github.com/trevorhobenshield/twitter-api-client/assets/34707863/566e5c92-da2f-4f36-9ea2-519b695ced97)
home_timeline doesn't exist under account either

**Comment by JackCrispy** [comment]
didn't catch this, but for some reason it is installing an old version of the package. 
![image](https://github.com/trevorhobenshield/twitter-api-client/assets/34707863/421c57c8-ef8f-40b4-8e68-bf0f9bea6ab5)
