### ISSUE TITLE
Get user id by username [Suggestion]

### ISSUE THREAD

**Issue by Jrublgo** [trevorhobenshield/twitter-api-client#174]
So, I dont sure if post there but anywhere. I made it a bot for make management for list more quickly. However, add new members for user is not useful, so i made this function for find by name and get the id for add in the list, like i do in #117 

```python
  def getUserByName(self, screen_name: str):
        settings = {"screen_name": screen_name}
        user = self.v1('users/lookup.json', settings)
        userID = user[0]["id"]
        return userID
```

**Comment by trevorhobenshield** [comment]
Nice work, looks like you got it!

You can also use `scraper.users([...])` and then parse the IDs out of the response.
