### ISSUE TITLE
How to resume session using cookies?

### ISSUE THREAD

**Issue by wutsqo** [trevorhobenshield/twitter-api-client#176]
The `twitter.account` class doesn't have cookies parameter in its initializer

**Comment by h4n0** [comment]
I faced the same issue, and I've solved it by updating my python and pip to 3.10 and above, and then do the `pip3 install twitter-api-client` again. 

Because the latest version of twitter-api-client requires 3.10 python.

**Comment by trevorhobenshield** [comment]
Thanks for the question, cookies are always passed as a kwarg.
