### ISSUE TITLE
Login doesn't need Email

### ISSUE THREAD

**Issue by JerukPurut404** [trevorhobenshield/twitter-api-client#18]
email, username, password = '', '', ''
account = Account(username, password)
account.tweet('test 123')

This does work but if I included email it will get: 
line 4, in <module>
    account = Account('' , '', '')
TypeError: Account.__init__() takes 3 positional arguments but 4 were given

**Comment by trevorhobenshield** [comment]
You may need to install the latest version of the package. `Account` and `Scraper` both need an email to complete account verification challenges, which are now becoming more frequent.

**Comment by JerukPurut404** [comment]
twitter-api-client==0.5.7

Isn't this the newest version?

**Comment by trevorhobenshield** [comment]
> twitter-api-client==0.5.7
> 
> Isn't this the newest version?

https://pypi.org/project/twitter-api-client
