### ISSUE TITLE
how to sort followers() and following() 's return by time sort?

### ISSUE THREAD

**Issue by yousonnet** [trevorhobenshield/twitter-api-client#185]
when i fetch this 2 endpoints:
1.following will always return me a vogue following users list,which contains 2 parts,first part is first 20 users,it seems llike a random user list by twitter's algorithm for recommendation,second part is that the list[20:],which is time sorted,who following lately is on front of group.
 2.followers will always return a random number first part,it's very like following's first part,but number is not assure.then second part is that list[random_number:],which is also time sorted.
 how to distinguish time sorted part and random part for followers() function?any ideas?

**Comment by trevorhobenshield** [comment]
the responses will need to be parsed, then you can sort by your desired key, usually `created_at`. It should be a unix timestamp in seconds.
