### ISSUE TITLE
How can i  Use it for python versions <=3.10.

### ISSUE THREAD

**Issue by doffn** [trevorhobenshield/twitter-api-client#186]
I am tring to use it in python anywhere but python version <3.10.5. when i try to insta `pip install twitter-api-client -U` using it will install an older version (0.5.7). how can i use it on an older python versions?

**Comment by doffn** [comment]
Found out i Cannot

**Comment by trevorhobenshield** [comment]
Thanks for the question, currently python 3.10 is the lowest supported version. I've yanked the earlier releases in PyPI so that this confusion doesn't arise again in the future.
