### ISSUE TITLE
Scraper Proxy

### ISSUE THREAD

**Issue by zackh88** [trevorhobenshield/twitter-api-client#191]
How can I use Proxies with scraper? I am working on something that needs a larger amount of data to be scraped and that's why I am using multiple accounts for scraping. I don't want those accounts to be banned.

**Comment by trevorhobenshield** [comment]
Hey, thanks for the question.

Short answer, Twitter tracks rate limits at the account-level (i.e. switching IPs will not bypass rate limits). Spreading your accounts across multiple IPs is fine, but this raises a new suite of issues regarding Arkose challenges being generated in response to "logging in from a new..." or "suspicious attempt was made..."

How one avoids being banned is also somewhat hard to determine (asides from obvious breaches of terms) and I'm not certain that proxies will help avoid this.

I'll update the readme with some additional information about this.

**Comment by triatic** [comment]
@trevorhobenshield something has definitely changed recently for me, authentication cookies previously lasting weeks now are lucky to last a day. Also periodic requests to log in via a browser and complete Arkose challenges.

I'm not a "heavy user" so maybe this was happening before and the limits were reduced, but it's new for me. I always use the same IP address.

**Comment by zackh88** [comment]
Thanks for the reply. 
How many accounts do you think can be safely used for scraper on one IP if I am scraping at almost the rate limit 24/7 @trevorhobenshield ? 
Or the accounts would get banned for such activity.

**Comment by trevorhobenshield** [comment]
@zackh88 You'll have to test it out. Maybe you can research what reasonable Twitter traffic would look like from where your IPs are located (e.g. public place? medium sized office? coffee shop?)

**Comment by zackh88** [comment]
Thanks @trevorhobenshield

**Comment by trevorhobenshield** [comment]
No, so far the main trigger for arkose challenges is executing a login flow from an IP which differs from the previous session's IP (see session management section in settings).
