### ISSUE TITLE
Cannot parse JSON response 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [trevorhobenshield/twitter-api-client#194]
I get this error message, `Cannot parse JSON response 'NoneType' object has no attribute 'json'`, every so often from running `scraper.likes()`

What does it mean, and how can I avoid it? If I cant avoid it, how can I catch it?

**Comment by trevorhobenshield** [comment]
You'll need to specify a `limit` when calling most methods, otherwise they are unbounded (will paginate until they hit the rate limit), which is what causes that error.

**Comment by trevorhobenshield** [comment]
Yes you can use the last cursor from the previous results. I believe there is a short example in the readme.

**Comment by berkingurcan** [comment]
@SakiSakiSakiSakiSaki, @trevorhobenshield  Hello, is there any update or solution?

**Comment by trevorhobenshield** [comment]
Thanks @SakiSakiSakiSakiSaki 

To add onto this, using a cursor to resume pagination will work, but only within the bounds of what is allowed for a normal Twitter user.

There are enterprise endpoints, and other paid endpoints that allow for historical data access, but these are not within the scope of this library, as this library only deals with what is publicly accessible for free.
