### ISSUE TITLE
Rate Limit Retrieval Proposal

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [trevorhobenshield/twitter-api-client#196]
I made a post about this a few weeks ago, #182, without receiving a response. I'd like to provide more details:

Could we be supplied an independent function that returns the rate limit on a particular end point??
I found the following (paraphrased) code in `util.py`:
```py
def log(logger: Logger, level: int, r: Response):
    def stat(r, txt, data):
        limits = {k: v for k, v in r.headers.items() if 'x-rate-limit' in k}
        wait = int(r.headers.get('x-rate-limit-reset', current_time)) - current_time
        remaining = limits.get('x-rate-limit-remaining')
        limit = limits.get('x-rate-limit-limit')
```

I tried to reverse engineer it myself, but that is proving very difficult.

Something like this would be incredible:
`limits = scraper.get_limits(tweets_by_id())`

Just retrieve any of the three rate-limit values that you need. Wouldn't this just make it easier to time when to switch to another proxy instead of leaving it to uncontrolled race conditions?

---
If this were to get implemented, I'd even volunteer to do a write-up for it in the `readme.md`.

Or am I missing something? Is there an easier way of knowing when to went accounts / sleep that is documented somewhere that I'm not aware of?

Currently I'm just switching to a proxy via cookies, and sleeping for 60s every 10 tweets parsed from `tweets_by_id`, and I still hit the rate limit sometimes.

**Comment by trevorhobenshield** [comment]
Just added a property `rate_limits` which will now track these for each method.
```python
scraper.rate_limits
```

```
{
'favoriters': {
  '_endpoint': 'Favoriters',
    'x-rate-limit-limit': 500,
    'x-rate-limit-reset': 1711828807,
    'x-rate-limit-remaining': 497
  },
...
}
```

> Currently I'm just switching to a proxy via cookies, and sleeping for 60s every 10 tweets parsed from tweets_by_id, and I still hit the rate limit sometimes.

These rate limits are not tracked by IP, so a proxy/vpn will not do anything.

**Comment by trevorhobenshield** [comment]
@SakiSakiSakiSakiSaki just a heads up, i changed the `rate_limits` property to use the real GraphQL API op names instead of the function names. grabbing the function names at a hard-coded depth in the stack was causing problems for a few people.


E.g. it has been changed from this:
```python
{
  'tweets': {
    '_endpoint': 'UserTweets',
    'x-rate-limit': ...,
    'x-rate-limit-remaining': ...,
  }
}
```

to this:
```python
{
  'UserTweets': {
    'x-rate-limit': ...,
    'x-rate-limit-remaining': ...,
  }
}
```
