### ISSUE TITLE
The limit rate of tweets_details

### ISSUE THREAD

**Issue by Qggg** [trevorhobenshield/twitter-api-client#198]
Hi, Trevor
       You show the rate limit of tweets_by_ids and tweets_by_id, Could you tell about the rate limit of tweets_details? and Where I can find the number.

Thanks a lot

**Comment by trevorhobenshield** [comment]
I recently added a `rate_limits` property to the Scraper class. You'll just need to make an initial test query to populate it (This applies to all methods)

**Comment by Qggg** [comment]
> I recently added a `rate_limits` property to the Scraper class. You'll just need to make an initial test query to populate it (This applies to all methods)

It works, you genius.
