### ISSUE TITLE
support python version 3.9

### ISSUE THREAD

**Issue by kaykhan** [trevorhobenshield/twitter-api-client#20]
Would it be possible to lower the python version requirement?

Trying to deploy an application to lambda/edge function is proving difficult as currently a lot of the major providers only support python version 3.9.

**Comment by igorrocha** [comment]
I would also like that! Or at least Python >= 3.10, which is the latest supported runtime environment for AWS Lambda.

@kaykhan as a workaround, you can use a previous version of the lib. I'm using https://pypi.org/project/twitter-api-client/0.5.7/ for example, and it works with Python >= 3.9.7.

**Comment by trevorhobenshield** [comment]
Python version requirement has now been lowered to `3.10.10`
