### ISSUE TITLE
Locked accounts

### ISSUE THREAD

**Issue by akuma0** [trevorhobenshield/twitter-api-client#201]
Hello !
On the SearchTimeline GraphQL i regularly get errors 401/403 lead to account locked with Arkose Challenge. 
I'm the only one or it's normal ?

**Comment by triatic** [comment]
Normal. X wants to sell API subscriptions.

**Comment by akuma0** [comment]
For sure :D
i try to understand what led to this account ban, i've not found so far. Anybody else works on this problem ?

**Comment by trevorhobenshield** [comment]
Yes very common, large numbers of gql mutations (most Account methods) may trigger these locks/bans. If you are just scraping, bans are unlikely, even when hitting rate limits consistently.

**Comment by triatic** [comment]
I trip Arkose challenges regularly when using Search/Scraper methods well within rate limits, with a consistent IP address.
