### ISSUE TITLE
flow_token errors while logging in 

### ISSUE THREAD

**Issue by tarson96** [trevorhobenshield/twitter-api-client#205]
Hi, so i been using multiple accounts and proxies for logging in to the client, but after some while, flow_token errors start to come.

[error] failed to update token at flow_password
[error] failed to update token at flow_username

and these just continues for like an hour, then it logins fine automatically after that.

Pls fine the below screenshot, thanks

![Screenshot 2024-04-20 at 6 50 22 PM](https://github.com/trevorhobenshield/twitter-api-client/assets/20413123/e9bdbed6-5df3-4e36-b51f-83a7238c51f8)

**Comment by trevorhobenshield** [comment]
> using multiple accounts and proxies

logging in with the same account through different IPs almost always triggers an Arkose challenge, which is what is causing those errors.

you'll need to keep trying different proxies until one of them doesn't trigger an Arkose challenge, or you'll have to copy cookies and use those instead.

**Comment by tarson96** [comment]
any suggestions for proxies which i can use ? or for cookies ?
