### ISSUE TITLE
Scraper: Cannot parse JSON response 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by abd-ghreeb** [trevorhobenshield/twitter-api-client#206]
Whenever I try to use the scraper, I keep getting None responses with the error below

```
>>> tweets_details = scraper.tweets_details([1770164518758633590], count=100, limit=100)
TweetDetail: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.82s/it]
Cannot parse JSON response 'NoneType' object has no attribute 'json'

```
Is there a problem with the Scraper module?

**Comment by trevorhobenshield** [comment]
This is a common issue, usually this means your cookies have expired, a pending security challenge, rate limit, or an account block.

You can log-in using the browser and see if everything is working, then copy your cookies and run your script again.
