### ISSUE TITLE
Confirmation of tweets_by_ids endpoint rate limits

### ISSUE THREAD

**Issue by Vishalk30** [trevorhobenshield/twitter-api-client#209]
Hi Trevor,

Just wanted some clarity on the rate limits for tweets_by_ids. I see this on the chart:  tweets_by_ids: ~220 (batch size) 500 / 15 mins (rate limit). I just wanted to confirm that the 500/ 15 mins is referring to "500 batches of 220 tweet ids per 15 min" or in other words, a rate limit of around "110,000 tweet ids per 15 min". Is this assumption correct?

Thanks!

**Comment by trevorhobenshield** [comment]
Hey Vishal, yes that's correct! It's very efficient and should always be preferred, depending on what data you're looking for.
