### ISSUE TITLE
Unable to Authorize in Linux Shell

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [trevorhobenshield/twitter-api-client#210]
Trying to use this API in a script running on a VSP Linux shell.

Neither `Scraper()` nor `Account()`are working. Both return the following messages:
```bash
 Checklist:
                1. Log-in via the browser and confirm your account is not blocked, or has pending security challenges.
                2. Copy the `ct0` and `auth_token` cookies from the browser.
                3. Re-run your program using these new cookies.
```

I should preface that I've only recently come across this issue for Linux shell (about 10 days ago).

The following has not helped:
- Logging in via browser and confirming account is fine.
- Copying cookies from browser and authorizing that way.
- Changing my IP address.
- Changing my credentials.

---
Given that Linux shell doesn't have a visible browser, how am I to "log in" through that environment?

**Comment by trevorhobenshield** [comment]
those error messages indicate the library is running but you have some security challenges pending or expired cookies, so no linux-related issues there.

as for logging in, you just use chrome/firefox as per usual and copy your cookies.

**Comment by SakiSakiSakiSakiSaki** [comment]
Thanks for the swift response.

> you have some security challenges pending

I just logged onto a throwaway Twitter account on my main PC browser, an I do not see any challenges (nor in my email).

----

>expired cookies

From said browser, I copied the `cf0` and `auth_token` values, and inputted it as such
```py
scraper = Scraper(cookies={"ct0": CT0, "auth_token": AUTH_TOKEN}, save=False, debug=False, pbar=False)
test_call = scraper.tweets_by_ids([TEST_TWEET])[0]["data"]["tweetResult"][0]
```
On my main PC, `test_call` returns exactly what I would expect it to.
But on my Linux shell, I have once again received the same message:
```bash 
Checklist:
                1. Log-in via the browser and confirm your account is not blocked, or has pending security challenges.
                2. Copy the `ct0` and `auth_token` cookies from the browser.
                3. Re-run your program using these new cookies.
```

---
> as for logging in, you just use chrome/firefox as per usual and copy your cookies.

That's what I did as explained above. I logged into my main PC and bought those cookies over to the Linux shell. Same issue.

Do I have to log into Twitter via Chrome headless or something?

**Comment by trevorhobenshield** [comment]
huh, I actually have no idea why this is happening. Very strange, cookies/headers are the only thing that matter, unless every IP you use is somehow blacklisted.

one test you can do is copy a sample curl request (e.g. look for UserTweets endpoint in devtools) from your browser and try running that in the shell. if that doesn't work, then there is a fundamental issue with the shell, and it's something unrelated to twitter and this library.

**Comment by SakiSakiSakiSakiSaki** [comment]
> one test you can do is copy a sample curl request (e.g. look for UserTweets endpoint in devtools) from your browser and try running that in the shell.

Done, and this works. It returns full JSON data from the curl request.

---

As a follow up to that successful curl request...

Using the cookies of the same account, I then tried to run the following:
```py
import configparser

from twitter.scraper import Scraper

from utilities.helper import *

credentials_path = validate_directory("credentials")
config = configparser.ConfigParser(interpolation=None)
config.read(credentials_path / "config.ini")

TEST_TWEET = int(config["twitter"]["test_tweet"])
CT0 = config["twitter"]["ct0"]
AUTH_TOKEN = config["twitter"]["auth_token"]

scraper = Scraper(cookies={"ct0": CT0, "auth_token": AUTH_TOKEN}, save=False, debug=False, pbar=False)
test_call = scraper.tweets_by_ids([TEST_TWEET])
print(test_call)
```

Works on my main PC, but fails on my Linux shell (which has a different static IP address because it's a VSP).

The Twitter account isn't banned or suspended, do you think my IP address is banned? I'm gunna try to change my ipv4 address and get back to you. At least we're making progress.

-----
**Update:** Creating a new shell with a different IP address did not fix the issue, even with up-to-date cookies.
