### ISSUE TITLE
Question: How to get the user id from username?

### ISSUE THREAD

**Issue by molinto** [trevorhobenshield/twitter-api-client#218]
Hi, thanks for all your hard work on this project folks.

I'm trying to block a list of users, but I need the userid (https://github.com/trevorhobenshield/twitter-api-client/blob/main/twitter/account.py#L367), but I only have Twitter usernames.

The official docs, can take screen_name as a param (https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/mute-block-report-users/api-reference/post-blocks-create).

So question is, how to get the user id from username please?

**Comment by lijuuu** [comment]
did u find any way to do it?

**Comment by molinto** [comment]
> did u find any way to do it?

Try here for an example:
https://github.com/incandenza-11/blockout2024/commit/8db592c92db07a8947d31d57e2d3535acf9ea191#diff-38b1a045d7d575204f06272c38ba3a2d00ad906b102c245897b76135b355e70cR44

**Comment by trevorhobenshield** [comment]
Thanks for the question.

The user ID will need to be parsed from the JSON response returned by `scraper.users(["user1", "user2", ...])`
