### ISSUE TITLE
how to get replies given a tweet id?

### ISSUE THREAD

**Issue by singhdan2002** [trevorhobenshield/twitter-api-client#219]
Hi I have the original tweet data now I need the replies to it
is there any way how to achieve that in this repo?

**Comment by hypotyposis** [comment]
got the same question here. the `tweet_details` API returns multi entries like this, each contains a reply, but it just returns a small part of the replies, don't know how to get full replies yet.

**Comment by trevorhobenshield** [comment]
Thanks for the question.

That's interesting, `tweets_details` is indeed the correct method. It shouldn't be returning truncated replies. I'll have a look.
