### ISSUE TITLE
Support curl-cffi

### ISSUE THREAD

**Issue by JodanJodan** [trevorhobenshield/twitter-api-client#23]
While the client currently forges a Mozilla user-agent, Python is still distinguishable from real browser requests due to its OpenSSL usage. To provide some protection against Twitter implementing TLS fingerprinting against its GraphQL API, could you add optional support for [curl-cffi](https://github.com/yifeikong/curl_cffi), a wrapper for [curl-impersonate](https://github.com/lwthiker/curl-impersonate) / [curl-impersonate-win](https://github.com/depler/curl-impersonate-win)?

**Comment by trevorhobenshield** [comment]
Thanks for the feedback. Twitter seems to have very few bot detection mechanisms in place so this hasn't been necessary. I suspect when TLS fingerprinting becomes an issue, there will also be far greater issues that arise alongside it as well. Trying to proactively enumerate and evade all possible bot detection mechanisms will bloat the package severely, so I decided to keep things as simple as possible until a glaring issue arises.
