### ISSUE TITLE
More/updated documentation

### ISSUE THREAD

**Issue by D3SK3R** [trevorhobenshield/twitter-api-client#25]
Is there an updated or more complete documentation?
The one here or at pypi.org mentions, for example, the scraper.users() function, which doesn't exist, but I found the user_by_rest_id, I have to get this ID but after that it works as expected, and in the function scraper.tweets(), I see no arguments for limiting the results. I'm looking for a way to simply get the latest tweets' content for some accounts, but it's not clear how to optimally do it.

**Comment by trevorhobenshield** [comment]
Thanks for the feedback. Sounds like you're using an older version, make sure you have `0.7.6` installed. 

https://github.com/trevorhobenshield/twitter-api-client/blob/be83dfb86f133f5b98df12bd38d857ac5a571174/twitter/scraper.py#L55-L56


Example: pull latest 100 tweets from a group of users

```python
from twitter.scraper import Scraper

email, username, password = ..., ..., ...
scraper = Scraper(email, username, password) # optional: debug=1, save=True

user_ids = [...]

tweets = scraper.tweets(user_ids, limit=100)
```
