### ISSUE TITLE
ModuleNotFoundError: No module named 'twitter.search'; 'twitter' is not a package

### ISSUE THREAD

**Issue by Shifter2600** [trevorhobenshield/twitter-api-client#30]
I did have search working before but now I get an error ModuleNotFoundError: No module named 'twitter.search'; 'twitter' is not a package.

**Comment by trevorhobenshield** [comment]
Might have an older version, try:

```bash
pip uninstall twitter-api-client -y
pip install twitter-api-client --no-cache-dir
```

**Comment by Shifter2600** [comment]
Did that and it still is not working.
Successfully installed twitter-api-client-0.7.7
python.exe .\search.py
    from twitter.search import Search
ModuleNotFoundError: No module named 'twitter.search'; 'twitter' is not a package
