### ISSUE TITLE
Pagination info

### ISSUE THREAD

**Issue by igorrocha** [trevorhobenshield/twitter-api-client#31]
Is there a way I can get the pagination info from the scraper requests?

The reason I ask is because I'm trying to use multiple accounts to get all the followers for a given account, without reaching the API's rate limits. 

I would need to be able to start the scraping from the same pagination position where the previous account finished.

**Comment by trevorhobenshield** [comment]
Unfortunately it's all cursor-based.

If they were represented simply as `b64("userId-page-0")` I guess you could decode, parse, and save them to disk for later use. I haven't looked into this, though you can clearly tell some keys in their response data have been b64'd at least once or twice, which isn't uncommon.
