### ISSUE TITLE
Async Error

### ISSUE THREAD

**Issue by Jmallone** [trevorhobenshield/twitter-api-client#32]
When i use this method

```followers = scraper.followers([USER_ID])```

for me happens this error:
![image](https://user-images.githubusercontent.com/6977257/234961234-5ed2cbd3-b73e-4092-a895-c3309d0a4b6e.png)

how fix it?

**Comment by trevorhobenshield** [comment]
Looks like you're running it in colab, not sure how they handle things, maybe you can try `nest_asyncio.apply()` again.

As long as you're using the latest version (0.7.7) it should work. I ran some tests in notebooks locally today.
