### ISSUE TITLE
Using CLI

### ISSUE THREAD

**Issue by JanKov84** [trevorhobenshield/twitter-api-client#33]
Hello, is there a way to use the scraper from the CLI as I'm a great noob when it come to code writing in Python? Many thanks.

**Comment by trevorhobenshield** [comment]
Good point, I think a CLI would be useful, I'll look into it.

**Comment by JanKov84** [comment]
> Good point, I think a CLI would be useful, I'll look into it.

That would be great for "losers" like me. If you could look into it, I would be much grateful.
