### ISSUE TITLE
Debug Options

### ISSUE THREAD

**Issue by Survivian** [trevorhobenshield/twitter-api-client#35]
In the examples provided in the readme, there's two different debug values.
These are not elaborated on what the difference is.
Is debug 1 just for scrapers and debug 2 just for regular account stuff?
Do the debug options give different amounts of info?
Is it possible to parse specific parts of the debug info to not clog up the command line?

**Comment by trevorhobenshield** [comment]
Thanks for the feedback. The debug values are just verbosity levels.

**Comment by Survivian** [comment]
Is it also possible if you could add a separate debug parameter for disabling it logging into a .txt file?
Having that slowly creep up in my background process isn't exactly ideal.
