### ISSUE TITLE
400: Internal Server Error

### ISSUE THREAD

**Issue by Survivian** [trevorhobenshield/twitter-api-client#38]
```
2023-05-01 09:30:07,585.585 DEBUG: [[31merror[0m] 400
{
    "errors": [
        {
            "message": "Internal server error",
            "extensions": {
                "name": "InternalServerError",
                "source": "Server",
                "retry_after": 0,
                "code": 0,
                "kind": "Operational",
                "tracing": {"trace_id": "8d878e4f6abb553b"},
            },
            "code": 0,
            "kind": "Operational",
            "name": "InternalServerError",
            "source": "Server",
            "retry_after": 0,
            "tracing": {"trace_id": "8d878e4f6abb553b"},
        }
    ]
}
```
I'm unsure what to make of this error.
When having `debug=1` when logging in, it throws this error at me with a 400 code and then hangs.
I couldn't find anything equivalent in Twitter's API docs.
Does this have to do with the API itself dying or my own internet cutting out?
Is there something you could add in the future to parse out when errors like these happen so it can retry again without hanging any looping program forever?

**Comment by trevorhobenshield** [comment]
They're having issues on their end right now, this is likely the issue.
