### ISSUE TITLE
Allow search to be done only on recent tweets

### ISSUE THREAD

**Issue by Kamigaku** [trevorhobenshield/twitter-api-client#41]
Hello,

Right now, when you are using the Search function, you retrieve every tabs of the search (trending, recent, user, media, video). 
Is it possible to retrieve only one category? For example, i'd be interested in only retrieve result from the "Recent" tab, would it be possible?
After checking a little bit in the request done when using twitter, it seems that it can be done by adding the `tweet_search_mode: live` when requesting the `search` api endpoint.

**Comment by trevorhobenshield** [comment]
Good point, just added this. You can now add `latest=True` to achieve this. 

E.g.
```python
search.run(
    'paperswithcode -tensorflow -tf',
    'ios android',
    limit=100,
    latest=True,  # get latest tweets only
)
```
