### ISSUE TITLE
Using with multiple accounts

### ISSUE THREAD

**Issue by 0xGhostCasper** [trevorhobenshield/twitter-api-client#42]
Hello, thanks for wonderful library, 

my specific usecase involves extracting every single follower or following, but
with single account the GraphQL API limit is exceeded very quickly (50/15 min. for followers, 500/15min. for
followings). I therefore need to implement some kind of multi-acc support, so my questions would be:

1) Is there any way to achieve this right now by using this library and if not are there any plans
to add multi-account support with HTTP proxies support as using multi accounts on single IP is almost
certain ban?

2) Cursor support. Are there any plans? I need to pickup extracting followers/followings from where previous
account finished if rate limit is reached.

3) Is there a way to get remaining limits with this library?

**Comment by trevorhobenshield** [comment]
1. Sounds like a good idea, not currently planning to add this, maybe in the future.
2. Just added a method to support continued pagination from a specific cursor value. It's ugly but it works for now. See `resume_pagination` in the readme.
3. Remaining rate-limits are currently only logged, just need to set `debug` to 1 or greater and you'll see them. I'll look into storing them in Scraper object as well.
