### ISSUE TITLE
Latest=True not actually pulling latest results

### ISSUE THREAD

**Issue by Abolfazl** [trevorhobenshield/twitter-api-client#47]
I have some simple code to pull the latest tweets with a given domain. However the results saved are definitely not the latest.

    from twitter.search import Search
    search = Search(EMAIL, USERNAME, PASSWORD)
    search.run('(viralsweep.com or swee.ps)', limit=100, latest=True)

This code returns tweets that were created in February 2022, July 2022, October 2022 but there have definitely been [more tweets](https://twitter.com/search?q=(viralsweep.com%20or%20swee.ps)&src=typed_query&f=live) when I search for this query on Twitter.com

Am I doing something wrong? Could it be the code?

**Comment by lucasg1** [comment]
Maybe not what you are looking for, but you have to write **OR** with capital letters, otherwise it'll search also for the word "or".

**Comment by trevorhobenshield** [comment]
You'll want to ensure the results are parsed correctly. I've added another example notebook `examples/search.ipynb`. The `run` function is intended to execute multiple queries, resulting in a sub-list for each query's results. You'll inevitably need to flatten or index into those results.

**Comment by Abolfazl** [comment]
@lucasg1 My account is not locked or limited in any way.

@trevorhobenshield I know `search.run()` can execute multiple queries but I only have 1 query to run.

I just ran `search.run(f'gvwy.io since:2023-05-21', limit=100, latest=True)`. It only found 4 tweets despite the fact that the web search shows dozens that fit the search criteria.

[Here](https://pastebin.com/drp6YdQH) is the link to the JSON contents. This was the only file returned from this search.
