### ISSUE TITLE
Not Understanding Some Things

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [trevorhobenshield/twitter-api-client#49]
Hi,

My personal objective is to access my personal Liked Tweet list, and download said Tweets.

I have a few questions:
- In `email, username, password = ..., ..., ...`, am I supposed to fill in my information in string formats, like so?
`email, username, password = 'JohnDoe@hotmail.com', 'JohnDoe', 'JohnDoe123'` ?

- `scraper = Scraper(email, username, password, debug=1, save=True)` gives me the error `__init__() got an unexpected keyword argument 'debug'`. Is `scraper = Scraper(username, password)` the intended format?

- For something like `likes = scraper.likes([123, 234, 345])`, am I supposed to insert my Twitter ID in that list? When I did so, I got the following error, `TypeError 'NoneType' object is not subscriptable`

If there's any documentation available, I would love to see it. Thank you.

**Comment by krruzic** [comment]
1. Yes that's how you fill it in
2. debug needs to be a boolean, `True` or `False` the readme is outdated I think, pass it in after `save` and make sure you're using the latest version of the package
3. You're supposed to insert the ID of a user there. You can get the ID of a user through `scraper.users([user_screen_name])` where `user_screen_name` is your @. 
```
import base64
user_info = scraper.users([user_screen_name])
user_id_b64 = user_info[0][0]["data"]["user"]["result"]["id"]
user_id = int(base64.b64decode(user_id_b64).decode().split(":")[1])

# get likes for user_id
scraper.likes([user_id])
```

There isn't really any documentation I recommend reading through the code.

**Comment by loby66** [comment]
install python 3.11
