### ISSUE TITLE
New login to Twitter from ChromeMobileAndroid on Android

### ISSUE THREAD

**Issue by briankariuki** [trevorhobenshield/twitter-api-client#50]
I want to automate an account. Everytime I login I get this notification from twitter. Will I be banned if I login frequently? Like every one to two minutes to publish a tweet?

**Comment by trevorhobenshield** [comment]
It might look a bit suspicious. I've tested this before and I've gotten a few email confirmation challenges. It's hard to predict the frequency at which they issue these challenges, or what indicators they have. I would suggest just modifying your program, letting your account object have global scope for example.
