### ISSUE TITLE
Adding same api methods but in async

### ISSUE THREAD

**Issue by ExHix** [trevorhobenshield/twitter-api-client#51]
I want to use this package on my bot, and I prefer to use async method to avoid network congestion. For example, I briefly read the account.py and found that most of the methods are calling `gql()` which use `self.session.request` to make request, and the seesion is from `httpx.Client()`. To make it async maybe we just need to replace `httpx.Client()` as `httpx.AsyncClient()` and make other changes accordingly. It might be easy to implement other async method in the same way?

**Comment by trevorhobenshield** [comment]
I decided against this for a few reasons, but I may revisit this idea.

One reason this would not be a good idea is that user interactions on Twitter are generally sequential, i.e. if Bob makes 1 tweet about Big Bird, Bob is just a fun guy. His account interaction makes sense. If Twitter's servers process 11 tweets about Big Bird, 7 replies regarding Ernie, and 3 quote-tweets implicating Bert all in the span of 5 seconds, Bob is clearly doing some shit.
