### ISSUE TITLE
ModuleNotFoundError: No module named 'twitter.util'

### ISSUE THREAD

**Issue by pepeto** [trevorhobenshield/twitter-api-client#52]
After installing the library, pip install twitter-api-client, I receive this message when executing

from twitter.util import find_key

thank you!

**Comment by trevorhobenshield** [comment]
Try re-installing, that util file should always be there.

```bash
pip install twitter-api-client==0.8.0
```

or

```bash
pip uninstall twitter-api-client -y
pip install twitter-api-client==0.8.0 --no-cache-dir
```
