### ISSUE TITLE
How to exclude promoted tweets from search?

### ISSUE THREAD

**Issue by carlosdcuba1** [trevorhobenshield/twitter-api-client#54]
When I get messages from a search result, promoted tweets are included. Exist any way to remove it?

Thank you

**Comment by trevorhobenshield** [comment]
Can you provide a sample response containing promoted tweets? None of my test searches return promoted results.

**Comment by carlosdcuba1** [comment]
I'm sorry, but this type of message does not appear every time and I realized the result when I saw that there was nothing related to the search term I used in their content. Thank you for your attention, as soon as I get messages of this type again I will send you the data

**Comment by carlosdcuba1** [comment]
After some tests I could find that the promoted Tweets are the ones that come in the TIMELINE (below the GlobalObjects) with the following values (promotedMetadata)

```
{
"entryId": "sq-I-t-1658838449288278017",
"sortIndex": "999970",
"content": {
"item": {
    "content": {
        "tweet": {
            "id": "1658838449288278017",
            "displayType": "Tweet",
            "promotedMetadata": {
                "advertiserId": "212632603",
                "impressionId": "21c5a3550a820bce",
                "disclosureType": "NoDisclosure",
                "experimentValues": {
                    "website_card_variation": "0"
                },
                "promotedTrendId": "0",
                "clickTrackingInfo": {
                    "urlParams": {
                        "twclid": "2-2zl6ot697aq18dqs9e1ha1j0d"
                    }
                }
            }
        }
    },

```

To identify them from the results apply the following:

```
def get_promoted_tweets(self, data):
        if 'timeline' in data:
            entries = data['timeline']['instructions'][0]['addEntries']['entries']        
            for e in entries:
                if 'item' in e['content']:
                    tweet = e['content']['item']['content']['tweet']
                    if 'promotedMetadata' in tweet:
                        print(tweet['id'], '- Promoted Tweet -', self.query, flush=True)
                        self.promoted_tweets.append(tweet['id']) if tweet['id'] not in self.promoted_tweets else self.promoted_tweets
```

One more time, thanks for your contribution

**Comment by lucasg1** [comment]
See https://github.com/trevorhobenshield/twitter-api-client/blob/main/examples/search.ipynb

The way that it is implemented right now is that you have to do a post-processing to get rid of this "garbage" that you don't want

Just ignore these "timeline" objects if you don't want to see these promoted tweets
