### ISSUE TITLE
unable to do scraping:

### ISSUE THREAD

**Issue by rinaldi6109** [trevorhobenshield/twitter-api-client#56]
Running the code:
```
from twitter.scraper import Scraper

email, username, password = ...,...,...
scraper = Scraper(email, username, password, debug=1, save=True)

trends=scraper.trends()

tweets=scraper.tweets_by_ids([1657520327642030080,1656325838466347010])
```

I get empty `trends={} `and the following error for `tweets`:
`AttributeError: 'Scraper' object has no attribute 'tweets_by_ids'` 

What's wrong?
Thank you.

**Comment by rinaldi6109** [comment]
Whereas if I run:
```
tweets=scraper.tweets([1657520327642030080,1656325838466347010])
```
I get:
```
[RuntimeError: asyncio.run() cannot be called from a running event loop
](url)
```

**Comment by trevorhobenshield** [comment]
1. Ensure you're using version `0.8.1` or greater, I stupidly ended up changing some of the method names/signatures. `tweets_by_ids()` was changed to `tweets_by_id()` at some point.
2. `scraper.tweets()` takes a list of user ids, it looks like you're passing tweet ids. I need to create some better documentation for this. For now, you can see in the method signatures what types of ids are required.

**Comment by pothitos** [comment]
Thank you very much for your work, Trevor!

Regarding this issue, I get an empty `{}` JSON file after executing

```python
from twitter.scraper import Scraper

## sign-in with credentials
email, username, password = ..., ..., ...
scraper = Scraper(email, username, password)

# trends
scraper.trends()
```

Is it me or trends cannot be retrieved?

**Comment by pothitos** [comment]
If someone has the same problem with me, you can try this [patch](https://github.com/socileaks/twitter-api-client/commit/e634ab0488f58813cf01ca74793c8a534fe0bc41) 😉
