### ISSUE TITLE
What Is `cursor` supposed to be?

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [trevorhobenshield/twitter-api-client#58]
Can someone tell me what I'm supposed to set `cursor` to for paginating my likes?

Also, what is the purpose of `|` ?

**Comment by trevorhobenshield** [comment]
The `|` symbol is just part of the cursor. Cursors can usually be found as the last two entries of a large `entries` array and come in different formats and encodings. Please see the readme for an example.

E.g.
```json
{
    "entryId": "cursor-top-1766674352934427551",
    "sortIndex": "1766674352934427551",
    "content": {
        "entryType": "TimelineTimelineCursor",
        "__typename": "TimelineTimelineCursor",
        "value": "HCa87piH172+hDEAAA==",
        "cursorType": "Top"
    }
},
{
    "entryId": "cursor-bottom-1766653496099534368",
    "sortIndex": "1766653496099534368",
    "content": {
        "entryType": "TimelineTimelineCursor",
        "__typename": "TimelineTimelineCursor",
        "value": "HBbC2LfD0/+0hDEAAA==",
        "cursorType": "Bottom",
        "stopOnEmptyResponse": true
    }
}
```

**Comment by trevorhobenshield** [comment]
> When I begin pagination, am I supposed to put `sort_index` in the cursor?

Nope, you use the cursor's `value` attribute.

> If so, how would I find that value, if I hadn't run pagination yet?

Cursors are usually the last two entries of a large `entries` array in your response object. They may have different formats and encodings.

> Is there another way I'm supposed to retrieve the them prior to doing the pagination?

You'll need to search your response object for "cursor" and you'll find the cursor objects

**Comment by trevorhobenshield** [comment]
Taking a look at your initial question, I think I could have given you a more succinct answer to begin with.

If your goal is just to **pull all liked tweets from someone's account** pagination is already done for you. 

The function `resume_pagination()` is only meant for two special cases:

1. The target account has an extremely large amount of data (many likes, tweets, followers, etc.) that will not be able to be processed in one session.
2. You wish to pull all followers from a target account. This endpoint has an very low rate limit of 50 requests per 15 mins

> Does the response object have a cursor attribute? Like response.cursor?

You would simply pass your last response to the utility function `get_cursor()` to retrieve the cursor.

> If you have some example code that you use to paginate Likes or Followers that I could use as reference

Please see the readme. I have an example for Followers. Likes will also follow the same approach. As for what the cursors look like it doesn't matter, if you want to decode them you can. They're using React and Apollo https://www.apollographql.com/docs/react/pagination/cursor-based/

**Comment by trevorhobenshield** [comment]
> I only seem to be getting the first 101 of my likes. I have 100x that amount, so pagination would be necessary.

Manual pagination is not needed.

Here is an example of pulling 10,000 likes which meets your criteria.

```python
from twitter.scraper import Scraper

email, username, password = ..., ..., ...
scraper = Scraper(email, username, password, debug=1, save=True)

user_ids = [44196397] # user with many likes, e.g. Elon Musk
tweets = scraper.likes(user_ids, limit=10_000)
```

The average number of results returned by each call to their GraphQL `/Likes` endpoint is ~150. This means you can theoretically pull ~75,000 likes within the rate-limit restriction of 500 requests/15 mins. All pagination is done for you already. If you hit that limit, you should then use `resume_pagination()`.

> As an aside, what does limit do? Changing it's value doesn't seem to change the number of results each call retrieves. Is that supposed to be the number of pages that would be retrieved? Kinda confused on that, cause changing the limit to 1, still has second_likes_subset retrieve results. Or maybe it's zero indexed?

The `limit` is the total number of unique results (tweets, likes, followers, etc.) returned.

**Comment by trevorhobenshield** [comment]
The `variables` URL param contains a key `count` which determines how many results to return per query. You'll notice I've set it to a large arbitrary number to try and "max-out" each request, which is what causes ~100 results to be returned each time by default. Some endpoints only return ~20 results, others can return close to 200 results.

**Comment by trevorhobenshield** [comment]
Sure, what do you think I should update, add, or provide clearer explanations for?
