### ISSUE TITLE
Name collisions

### ISSUE THREAD

**Issue by reagle** [trevorhobenshield/twitter-api-client#59]
Thank you for this package! Keeping up with the official API is now painful. However, I believe we import this package as "twitter" which is likely to collide with other modules. Could you give it a different name, like "twitter-scraper" or some such thing?

**Comment by trevorhobenshield** [comment]
Thanks for the feedback. This makes sense, I'll see if I can come up with a good solution.

**Comment by reagle** [comment]
It's kind of odd to close this as completed when it's not done...?
