### ISSUE TITLE
Aborts: "loading libcrypto in an unsafe way"

### ISSUE THREAD

**Issue by reagle** [trevorhobenshield/twitter-api-client#60]
I've never seen an error like this before:

```
In [2]: from twitter.account import Account
WARNING: /Users/reagle/.pyenv/versions/3.11.0/bin/python3 is loading libcrypto in an unsafe way
[1]    96622 abort      ipython
```

**Comment by trevorhobenshield** [comment]
Interesting, this is likely due to the protonmail module I added, although I haven't gotten this error yet. What OS are you using?

**Comment by reagle** [comment]
OS: macOS 13.3.1 22E261 arm64

**Comment by Ian-Bright** [comment]
Same issue

**Comment by reagle** [comment]
@Ian-Bright, are you using an M1 or M2? Did you use pyenv? [Here's what perplexity.ai has to say](https://www.perplexity.ai/search/7cd12c33-c07a-41b5-838d-8afdec6160d3?s=u).

> The root cause of this error is that the libcrypto library is being loaded dynamically at runtime, and the dynamic linker is unable to verify that the library has not been tampered with. This can happen if the library has been modified or if it is being loaded from an untrusted location
[1](https://stackoverflow.com/questions/59081569/executing-a-script-that-is-loading-libcrypto-in-an-unsafe-way-on-macos-10-15-1)
[2](https://python-forum.io/thread-38242.html)
.

> To fix this issue, one solution is to rebuild Python with a version of OpenSSL that is compatible with the macOS system. Another solution is to install a version of Python that has been built with a compatible version of OpenSSL, such as the version of Python that is installed using Homebrew
[2](https://python-forum.io/thread-38242.html)
.

**Comment by reagle** [comment]
I found it does work if I install the pre-proton version: `pip install git+https://github.com/trevorhobenshield/twitter-api-client@bf88a527e240a02763c944122244c774efcaa3fd`

**Comment by trevorhobenshield** [comment]
> If this library is dependent on "proton-python-client", I can't even install that on macOS 13.3.1 22E261 arm64.

I've decided to temporarily remove the protonmail dependency until I can figure out a clean way to support more systems (not just arch/debian/fedora)

Try installing this new version
```bash
pip uninstall twitter-api-client -y
pip install twitter-api-client==0.8.5
```

**Comment by Ian-Bright** [comment]
Thanks @trevorhobenshield this worked
