### ISSUE TITLE
Disabling Login Print

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [trevorhobenshield/twitter-api-client#61]
Would it be possible for this package to have an object that would allow one to configure details such as whether the `login failed`/`login success` message prints in the `login()` function?

Something like,
```py
login(login_print = False)
```

I'm aware I can do the following:
```py
def login(email: str, username: str, password: str) -> Client:
    session = Client()
    session.cookies.update({
        "email": email,
        "username": username,
        "password": password,
        "guest_token": None,
        "flow_token": None,
    })
    session = execute_login_flow(session)
    #if session.cookies.get('flow_errors') == 'true':
        #print(f'[{RED}error{RESET}] {BOLD}{username}{RESET} login failed')
    #else:
        #print(f'[{GREEN}success{RESET}] {BOLD}{username}{RESET} login success')
    return session
```
But I really don't like messing around with the functions packages come with, especially if I have to update the package and have my changes overwritten. I'd submit a PR, but I wouldn't know how to get all of the other objects to reference this `login` object for whether they should print or not.

Thoughts?

**EDIT:** Thinking about it more, I think a simple toggle to disable all prints to the console from this package would be better, since there's also the "suspicious activity" message that displays when you change your IP address.

**Comment by trevorhobenshield** [comment]
tqdm progress bars can now be turned off by setting `pbar=False`

E.g.
```python
scraper = Scraper(email, username, password, pbar=False)
```
