### ISSUE TITLE
Authorization: Denied by access control: Requires a writable access token; Missing LdapGroup(timelines-infra)

### ISSUE THREAD

**Issue by xjabr** [trevorhobenshield/twitter-api-client#63]
Hello, I tried to make a retweet and put a like to a tweet.

But the retweet gives back to me this error with this function `account.like(tweet_id)`:
`Expecting value: line 1 column 1 (char 0)`

And the `account.retweet(tweet_id)` gives back to me this error:
`{'errors': [{'message': 'Authorization: Denied by access control: Requires a writable access token; Missing LdapGroup(timelines-infra)', 'locations': [{'line': 2, 'column': 3}], 'path': ['favorite_tweet'], 'extensions': {'name': 'AuthorizationError', 'source': 'Client', 'code': 37, 'kind': 'Permissions', 'tracing': {'trace_id': 'fa7015087f4e6752'}}, 'code': 37, 'kind': 'Permissions', 'name': 'AuthorizationError', 'source': 'Client', 'tracing': {'trace_id': 'fa7015087f4e6752'}}], 'data': {}}`

The login flow was completed successfully but I don't know why I can't do write-operations.

`twitter-api-client` version `0.8.3`
`python` version `3.11.3`

**Comment by trevorhobenshield** [comment]
Unfortunately I cannot replicate this error.

Issues -> solutions:
1. Rate limiting has occurred  -> switch accounts and IP's
2. Account has been banned     -> switch accounts and IP's
3. Pending arkose challenge    -> sign-in in web app and complete arkose challenge
