### ISSUE TITLE
There was a login to your account ... from a new device on Jun 02, 2023. Review it now.

### ISSUE THREAD

**Issue by reagle** [trevorhobenshield/twitter-api-client#64]
Every time I run my script, Twitter notifies me of a new login from a new device. Is there a provision for persistence or saving a cookie?

**Comment by trevorhobenshield** [comment]
Two ways to prevent this:

1. Re-using the authenticated `self.session` object.
```python
email, username, password = ...,...,...
scraper = Scraper(email, username, password)
session = self.session

# do work
...

# reference authenticated session without logging in again.
new_scraper = Scraper(session=session)
```

2. Manually building an authenticated session with `ct0` and `auth_token` cookies


```python

# using cookies obtained from previous log-in
session = Client(cookies={
    'ct0': ...,
    'auth_token': ...,
})

scraper = Scraper(session=session)
```

**Comment by trevorhobenshield** [comment]
Sure, here's an example:

```python
import orjson
from httpx import Client
from pathlib import Path
from twitter.scraper import Scraper

email, username, password = ..., ..., ...
scraper = Scraper(email, username, password)

# write cookies
cookies = {k:v for k,v in scraper.session.cookies.items() if k in {'ct0','auth_token'}}
Path('twitter.cookies').write_bytes(orjson.dumps(cookies))
```


```python
# read cookies
cookies = orjson.loads(Path('twitter.cookies').read_bytes())
scraper = Scraper(session=Client(cookies=cookies))
```

**Comment by reagle** [comment]
Thanks! It kind of works, but fails when uploading media the second time and I'll need to figure how to manage cookies expiring. 

```
def twitter_update(
    comment: str, title: str, url: str, tags: str, photo_path: Path | None
) -> None:
    """
    Updates the authenticated Twitter account with a tweet and optional photo.
    """

    # https://github.com/trevorhobenshield/twitter-api-client
    import orjson
    from httpx import Client
    from twitter.account import Account
    from twitter.util import init_session

    from config import TMP_DIR
    from utils.web_api_tokens import (
        TW_EMAIL,
        TW_PASSWORD,
        TW_USERNAME,
    )

    # https://github.com/trevorhobenshield/twitter-api-client/issues/64
    cookies_fp = Path(TMP_DIR + "twitter.cookies")
    # TODO: deal with expired cookies 2023-06-06
    if cookies_fp.exists():
        cookies = orjson.loads(cookies_fp.read_bytes())
        session = Client(cookies=cookies)
        account = Account(session=session)
        info(f"using existing {cookies=}")
    else:
        session = init_session()
        account = Account(email=TW_EMAIL, username=TW_USERNAME, password=TW_PASSWORD)
        cookies = {
            k: v
            for k, v in account.session.cookies.items()
            if k in {"ct0", "auth_token"}
        }
        cookies_fp.write_bytes(orjson.dumps(cookies))
        info(f"using new {cookies=}")

    # TODO: prompts too many cookie exception on 2nd use: 2023-06-06
    # CookieConflict: Multiple cookies exist with name=ct0
    if photo_path:
        shrunk_msg = shrink_message("twitter", comment, title, "", tags)
        account.tweet(shrunk_msg, media=[{"media": str(photo_path)}])
    else:
        shrunk_msg = shrink_message("twitter", comment, title, url, tags)
        account.tweet(shrunk_msg)
```

**Comment by code-switched** [comment]
> Thanks! It kind of works, but fails when uploading a media tweet the second time and I'll need to figure how to manage cookies expiring. Suggestion welcome.
> 
> ```
> def twitter_update(
>     comment: str, title: str, url: str, tags: str, photo_path: Path | None
> ) -> None:
>     """
>     Updates the authenticated Twitter account with a tweet and optional photo.
>     """
> 
>     # https://github.com/trevorhobenshield/twitter-api-client
>     import orjson
>     from httpx import Client
>     from twitter.account import Account
>     from twitter.util import init_session
> 
>     from config import TMP_DIR
>     from utils.web_api_tokens import (
>         TW_EMAIL,
>         TW_PASSWORD,
>         TW_USERNAME,
>     )
> 
>     # https://github.com/trevorhobenshield/twitter-api-client/issues/64
>     cookies_fp = Path(TMP_DIR + "twitter.cookies")
>     # TODO: deal with expired cookies 2023-06-06
>     if cookies_fp.exists():
>         cookies = orjson.loads(cookies_fp.read_bytes())
>         session = Client(cookies=cookies)
>         account = Account(session=session)
>         info(f"using existing {cookies=}")
>     else:
>         session = init_session()
>         account = Account(email=TW_EMAIL, username=TW_USERNAME, password=TW_PASSWORD)
>         cookies = {
>             k: v
>             for k, v in account.session.cookies.items()
>             if k in {"ct0", "auth_token"}
>         }
>         cookies_fp.write_bytes(orjson.dumps(cookies))
>         info(f"using new {cookies=}")
> 
>     # TODO: prompts too many cookie exception on 2nd use: 2023-06-06
>     # CookieConflict: Multiple cookies exist with name=ct0
>     if photo_path:
>         shrunk_msg = shrink_message("twitter", comment, title, "", tags)
>         account.tweet(shrunk_msg, media=[{"media": str(photo_path)}])
>     else:
>         shrunk_msg = shrink_message("twitter", comment, title, url, tags)
>         account.tweet(shrunk_msg)
> ```

Did you find a solution for this @reagle?

I'm using httpx version 0.24.1 and inside of _models.py if you comment out line 1091:
`raise CookieConflict(message) `

The script runs as expected.

I'm sure this isn't ideal but it works for now.

I can't seem to wrap my mind around how to deal with httpx's Client other than ignoring the cookie issue or starting a new session completely.

**Comment by reagle** [comment]
No, not yet.

**Comment by trevorhobenshield** [comment]
@code-switched @reagle Issue should now be resolved in latest fix. If it happens again, try removing the csrf token for `.twitter.com`

e.g.
```python
scraper.session.cookies.delete('ct0', domain='.twitter.com')
```

**Comment by reagle** [comment]
Thank you; I deleted my old cookie; sent a test tweet to obtain a new one; and then tweeted with a media upload, twice, and it seemed to work.  Without sending a "normal" (test) tweet, tweeting the photo had an error: 

```Exception: {"errors":[{"code":353,"message":"This request requires a matching csrf cookie and
header."}]}```

**Comment by code-switched** [comment]
> @code-switched @reagle Issue should now be resolved in latest fix. If it happens again, try removing the csrf token for `.twitter.com`
> 
> e.g.
> 
> ```python
> scraper.session.cookies.delete('ct0', domain='.twitter.com')
> ```

Thank you! Can confirm this works as expected after updating to `0.9.8`

I came across a few httpx issues that described a similar problem, tinkering around with those were on my todo list but I appreciate you for resolving this so quickly!
