### ISSUE TITLE
Is `scraper.users_by_ids()` No Longer Supported?

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [trevorhobenshield/twitter-api-client#66]
I updated the package to version `0.8.5` on my test repo, and I discovered scraper.users_by_ids() returns an error, that wasn't found in my `0.7.x` version:

```py
user = scraper.users_by_ids([USER_ID])

> AttributeError: 'Scraper' object has no attribute 'users_by_ids'
```

I still read it as a method in the `READ.ME`, so I'm a little stumped.

Thanks.

**Comment by trevorhobenshield** [comment]
Thanks for spotting this. I accidentally renamed this one during refactoring.
