### ISSUE TITLE
Authorization fails & Account class missing kw

### ISSUE THREAD

**Issue by codilau** [trevorhobenshield/twitter-api-client#71]
Hi,
Giving a spin to this project, I have trouble at the second step already,
Initializing the Account class as in the example provided:
**account = Account(email, username, password, debug=2, save=True)**
raises TypeError
**TypeError: Account.__init__() got an unexpected keyword argument 'debug'**
am I missing something?
Also, it seem to work with only username/password but fails authentication:
**{my username} logged in successfully
2023-06-07 11:54:27,234.234 DEBUG: [ERROR]: {'errors': [{'message': 'Authorization: Denied by access control: unspecified reason', {...continues}** 

I tried 2 accounts, no two-factor auth, just simple user/password login.

**Comment by codilau** [comment]
So the version installed by the recommended pip command is v0.5.7 which seems to differ quite a bit.
In one of your exemples, you cite v0.9.0 so installed that one.
Now the code exeple takes the extra arguments, however, the login still fails.

**[warning] email confirmation code challenge.
[success] {username} login success
2023-06-07 12:43:36.200 [ERROR] :: [error] 200 {'errors': [{'message': 'Authorization: Denied by access control: unspecified reason', 'locations': [{'line': 2, 'column': 3}], 'path': ['list'], 'extensions': {'name': 'AuthorizationError', 'source': 'Client', 'code': 37, 'kind': 'Permissions', 'tracing': {'trace_id': 'c0a34055e7c50f02'}}, 'code': 37, 'kind': 'Permissions', 'name': 'AuthorizationError', 'source': 'Client', 'tracing': {'trace_id': 'c0a34055e7c50f02'}}], 'data': {}}**

**Comment by trevorhobenshield** [comment]
The issues you're describing all relate to auth checks and security challenges, in which case there isn't much else you can do other than trying different IP's and accounts until one combination works.

**Comment by 0xTiger** [comment]
Just to clarify @trevorhobenshield:
If I see:
```
In [1]: scraper = Scraper(email, username, password, debug=2)
[warning] email confirmation code challenge.
[success] {username} login success
```
Then the `[warning] email confirmation code challenge.` means I cannot use `scraper.likes`, `scraper.following` etc.?

**Comment by trevorhobenshield** [comment]
That message is basically saying you have to go into the web app and manually enter the code found in your email in order to log in again. You can continue making requests regardless of this, but you will be restricted to unauthorized endpoints like you described. 

I used to have an automated solver for people with protonmail accounts, but there were some issues running it on Mac. I'll be adding it back in once I can provide a clean working implementation.
