### ISSUE TITLE
Possible to stream timeline, like with tweetdeck?

### ISSUE THREAD

**Issue by mangaroo** [trevorhobenshield/twitter-api-client#73]
Thank you for this, I was wondering if it was possible to just stream my timeline like with tweetdeck?

There's mentions of:
timeline = account.home_timeline()
latest_timeline = account.home_latest_timeline(limit=500)

but I get:

AttributeError: 'Account' object has no attribute 'home_timeline'

Kind regards

**Comment by trevorhobenshield** [comment]
Thanks for the question, it looks like you're using an older version of the package.

Try:

```bash
pip install twitter-api-client==0.9.4
```
