### ISSUE TITLE
Importing tac leaves log.log files in current directory

### ISSUE THREAD

**Issue by reagle** [trevorhobenshield/twitter-api-client#74]
Here's an example of me using my command busy.py (which is importing but not using tac in this case) to "log" an air quality website. Notice it creates a file with the logger output.

```
❯ b j .test https://www.iqair.com/us/usa/massachusetts/boston
2023-06-09 12:54:59.186 [WARNING] ::
WARNING: This is a guest session, some endpoints cannot be accessed.

Scraping default Web page;
to log2work

❯ cat log.log
2023-06-09 12:54:59.186 [WARNING] ::
WARNING: This is a guest session, some endpoints cannot be accessed.
```

Again, this isn't scraping or posting to Twitter -- but the module is imported. And even if I was [scraping Twitter](https://github.com/reagle/thunderdell/blob/main/formats/scrape/twitter.py#L24) or [tweeting](https://github.com/reagle/thunderdell/blob/main/utils/web.py#L163), I have `save=False`.

I have `log.log` files all over the place from wherever I happen to invoke `busy.py`.

**Comment by trevorhobenshield** [comment]
`save` is meant to relate only to Twitter data capture. If you want to disable logging to disk you'll have to pass in a log config indicating the handlers to use.

E.g. only log to console

```python

log_config = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s.%(msecs)03d [%(levelname)s] :: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'standard',
            'stream': 'ext://sys.stdout',
        },
    },
    'loggers': {
        'twitter': {
            'handlers': ['console'],
            'level': 'DEBUG',
        }
    }
}

scraper = Scraper(email, username, password, debug=3, log_config=log_config)

```

**Comment by reagle** [comment]
Thanks for the update, trying it out:

1. Yes, log is now named `twitter.log` .
2. The `log_config` above does stop writing to twitter.log but then splurges it all over sys.stdout.
3. It's not pretty to have to include that config for "normal" behavior; I've never used a package where I had to define a custom logger config simply to import or use a module and keep it quiet.

Granted, my knowledge of logging is super simple, and in [my program](https://github.com/reagle/thunderdell/blob/main/busy.py#L247) I define only a simple logger where I set the log level threshold and an optional log file output.

```
    log_level = logging.ERROR  # 40
    if args.verbose == 1:
        log_level = logging.WARNING  # 30
    elif args.verbose == 2:
        log_level = logging.INFO  # 20
    elif args.verbose >= 3:
        log_level = logging.DEBUG  # 10
    LOG_FORMAT = "%(levelname).3s %(funcName).5s: %(message)s"
    if args.log_to_file:
        print("logging to file")
        logging.basicConfig(
            filename="busy.log",
            filemode="w",
            level=log_level,
            format=LOG_FORMAT,
        )
    else:
        logging.basicConfig(level=log_level, format=LOG_FORMAT)
```

**Comment by reagle** [comment]
Hello @trevorhobenshield, I still:

1. get the "[WARNING] :: This is a guest session, some endpoints cannot be accessed." 
2. and `twitter.log` files anywhere I've invoked my script that uses this library.

I understand you said I can configure a logger, but that's unusual (and a fair amount of code) just to use an API. Might you consider different default (silent) behavior?

**Comment by trevorhobenshield** [comment]
I will likely be keeping the warnings at the log-in step. I think it's important to know as soon as possible if restrictions are being applied.

As for the logger configuration, I will also likely be keeping it as is. The default option doesn't require any configuration. Even if you did choose to use a custom configuration, I would say there isn't more code to write. You would just define your custom configurations somewhere and import them into your program as necessary.

**Comment by reagle** [comment]
@trevorhobenshield, thank you for your patience on this. Let me try to explain my concerns. 

# Unnecessary noise from a library 

If I'm using scraper and don't log in, I get a warning. If I do login, then I get a "[success] user login success" and, then, if the cookies aren't working, I get tons of Twitter notifications. So for scraping, I'd prefer to do so anonymously. It's especially annoying when logging shows in program output -- HTML pages here.

<img width="631" alt="SCR-20230628-ngnx" src="https://github.com/trevorhobenshield/twitter-api-client/assets/596814/672a8b87-ef40-40ac-9959-ed312b28a362">

# Unnecessary code/filesystem pollution 

When I do use your library on the terminal, I end up with twitter.log files everywhere -- from wherever I invoke it. To turn it off, I have to configure a custom logger, which I've never had to do for any other library before. I could stick it in a module and import where necessary, but, again, I've never seen such a things before.


``` 
 from .default import ScrapeDefault

+LOG_CONFIG = {
+    "version": 1,
+    "disable_existing_loggers": False,
+    "formatters": {
+        "standard": {
+            "format": "%(asctime)s.%(msecs)03d [%(levelname)s] :: %(message)s",
+            "datefmt": "%Y-%m-%d %H:%M:%S",
+        },
+    },
+    "handlers": {
+        "console": {
+            "class": "logging.StreamHandler",
+            "level": "DEBUG",
+            "formatter": "standard",
+            "stream": "ext://sys.stdout",
+        },
+    },
+    "loggers": {
+        "twitter": {
+            "handlers": ["console"],
+            "level": "DEBUG",
+        }
+    },
+}
+
+
 session = init_session()
-scraper = Scraper(session=session, debug=1, save=False)
+scraper = Scraper(session=session, debug=1, save=False, log_config=LOG_CONFIG)
```

**Comment by trevorhobenshield** [comment]
I could start adding in extra logic to handle this, but I think I have to draw a line somewhere when things get too specific for a particular use case. For example, if stdout data is being written to your html then the issue isn't specific to my API, rather it generalizes to any process writing to stdout. Debugging in this API should really only be enabled on an ad-hoc basis as well.

Logging in this API is more of an "extra" feature I added and likely not something I will be modifying in the future, it's only intended use is really for mild debugging.

If others start to mention these same issues in the future I am open to revisiting them.

**Comment by reagle** [comment]
Hi @trevorhobenshield, forgive my confusion; I'm unfamiliar with logging beyond the simplest -- and have no experience with log_config. You wrote: "Debugging in this API should really only be enabled on an ad-hoc basis." Exactly, I don't want debugging from your module, but it seemed to be enabled by default and even now I don't know how to turn off the warning (if I don't log in) or the login message (if I do login). I don't even know what the numbers in the the argument `debug=3` mean.

**Comment by trevorhobenshield** [comment]
> I don't know how to turn off the warning (if I don't log in) or the login message (if I do login). I don't even know what the numbers in the the argument debug=3 mean.

When the debug argument is omitted it defaults to 0 and there should not be any logging. The numbers are just "cumulative verbosity" levels, I guess you could say. It just sets how much debug data you want to see.

> And I'm still getting twitter.log files everywhere. I don't want that either.

Just made another update, version `0.10.3` shouldn't have that issue anymore, as long as you omit the debug argument.

**Comment by reagle** [comment]
Thank you. When I omit or set it to 0 I get the following error:

```
/Users/reagle/.pyenv/versions/3.11.3/lib/python3.11/site-packages/twitter/scraper.py:815 in    │
│ _validate_session                                                                              │
│                                                                                                │
│   812 │   │   │   return _session                                                              │
│   813 │   │                                                                                    │
│   814 │   │   # no session, credentials, or cookies provided. use guest session.               │
│ ❱ 815 │   │   self.logger.warning(f'{RED}This is a guest session, some endpoints cannot be acc │
│   816 │   │   self.guest = True                                                                │
│   817 │   │   return session                                                                   │
│   818                                                                                          │
│                                                                                                │
│ ╭────────────────────────────── locals ───────────────────────────────╮                        │
│ │     args = (None, None, None, <httpx.Client object at 0x101849c50>) │                        │
│ │  cookies = None                                                     │                        │
│ │    email = None                                                     │                        │
│ │   kwargs = {'debug': 0, 'save': False}                              │                        │
│ │ password = None                                                     │                        │
│ │     self = <twitter.scraper.Scraper object at 0x1055e7210>          │                        │
│ │  session = <httpx.Client object at 0x101849c50>                     │                        │
│ │ username = None                                                     │                        │
│ ╰─────────────────────────────────────────────────────────────────────╯                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'warning'
```

**Comment by trevorhobenshield** [comment]
Just made more changes, `0.10.4` should now work

**Comment by reagle** [comment]
Working for me now; thank you!
