### ISSUE TITLE
Does the library support operations with DMs other than sending?

### ISSUE THREAD

**Issue by msvprogs** [trevorhobenshield/twitter-api-client#75]
Hello! Thanks for your great library.

I've searched through docs and code, but couldn't find how to retrieve received DMs (DM history) for user.
Does this library support scraping DMs for authorized user?
All I've found was `account.dm()` sending operation.
Also, can I delete DMs or conversation rooms?

Thanks!

**Comment by trevorhobenshield** [comment]
Thanks for the feedback, just added this in the readme. I added the search endpoint as well. 

```python

# get all messages from conversation
dms = account.dm_history(['12345-67890'])

# search messages from all conversations
dms = account.dm_search('test')

# delete conversation
account.dm_delete('12345-67890')

```

**Comment by msvprogs** [comment]
Wow, thanks a lot for the new endpoints! 👍 
As I understand, using these methods I can get history for specified conversations, search messages by keywords and delete the specified conversation.
But is there a way to get all conversation ids user is participating in? For example, to detect a new conversation from user which has sent message to the account.

**Comment by trevorhobenshield** [comment]
Thanks for the question, just added that functionality. This has been added to the readme

`account.dm_inbox()` will get you all conversation metadata

```python
# get DM inbox metadata    
inbox = account.dm_inbox()

# get DMs from all conversations    
dms = account.dm_history()

# get DMs from specific conversations
dms = account.dm_history(['123456-789012', '345678-901234'])

# search DMs by keyword
dms = account.dm_search('test123')

# delete entire conversation
account.dm_delete(conversation_id='123456-789012')

# delete (hide) specific DM
account.dm_delete(message_id='123456')
```

**Comment by msvprogs** [comment]
Thanks!! 👍

**Comment by msvprogs** [comment]
@JulienMaille 
Yes, I'm using this method to send DMs. It is called in the following way:
```python
result = self.account.dm("message text", [receiverUserId1, receiverUserId2, ...])
```
You should pass an array of user IDs.

**Comment by JulienMaille** [comment]
@msvprogs sorry to ping you again. Thanks for your great answer. Do you know if we can mark dms as read?

**Comment by msvprogs** [comment]
@JulienMaille 
As far as I know, this library doesn't support marking DMs as read yet, but it is theoretically possible (it should have been some GraphQL query, as I recall)

**Comment by JulienMaille** [comment]
@msvprogs I tried to find the endpoint from a repo that dumps the graphQL api but can't find any match
https://github.com/fa0311/TwitterInternalAPIDocument/blob/3f4df3c2d3762aca480a217a0437b04b0418b060/docs/json/API.json#L3953

**Comment by msvprogs** [comment]
@JulienMaille My bad, it wasn't a GraphQL query, but ordinary POST request with x-www-form-urlencoded payload:

`POST https://twitter.com/i/api/1.1/dm/conversation/<userid1>-<userid2>/mark_read.json`

Payload:
`conversationId=<userid1>-<userid2>&last_read_event_id=<last_read_message_id>`
