### ISSUE TITLE
[Feature request] Persistent cookie handling

### ISSUE THREAD

**Issue by triatic** [trevorhobenshield/twitter-api-client#77]
Following on from #64 

I think it would be very useful for twitter-api-client to save and load cookies natively, as well as handling the expiry times of the cookies. This would be of great use to people who run the program on a frequent basis and trigger a lot of Twitter login notifications.

Excellent application by the way!

**Comment by trevorhobenshield** [comment]
Thanks for the feedback, this has now been added.

E.g. 

```python
from twitter.scraper import Scraper

## sign-in with credentials
email, username, password = ..., ..., ...
scraper = Scraper(email, username, password)

## or, resume session using cookies
# scraper = Scraper(cookies={"ct0": ..., "auth_token": ...})

## or, resume session using cookies (JSON file)
# scraper = Scraper(cookies='twitter.cookies')

## or, initialize guest session (limited endpoints)
# from twitter.util import init_session
# scraper = Scraper(session=init_session())
```

Cookies should be OK to use for over a year, if they end up expiring sooner due to other factors I may look into this again in the future.
