### ISSUE TITLE
how to get the latest 1-5 tweets of some people using their twitter user name?

### ISSUE THREAD

**Issue by johnsmithodom** [trevorhobenshield/twitter-api-client#78]
Got confused by 
"
users = scraper.users(['foo', 'bar', 'hello', 'world'])
users = scraper.users_by_ids([123, 234, 345])  # batch-request
tweets = scraper.tweets([123, 234, 345])
likes = scraper.likes([123, 234, 345])
tweets_and_replies = scraper.tweets_and_replies([123, 234, 345])
media = scraper.media([123, 234, 345])
following = scraper.following([123, 234, 345])
followers = scraper.followers([123, 234, 345])
scraper.tweet_stats([111111, 222222, 333333])
"

have tried: 
>>> from twitter.scraper import Scraper
>>> email, username, password = 'cxxxx@gmail.com', 'myuserName', 'password'
>>> scraper = Scraper(email, username, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Scraper.__init__() takes 3 positional arguments but 4 were given
>>>

**Comment by trevorhobenshield** [comment]
Thanks for the question. Please ensure you've installed version `0.9.6` or greater. Those values in the readme are just placeholders.
