### ISSUE TITLE
Persistent cookie handling usage

### ISSUE THREAD

**Issue by triatic** [trevorhobenshield/twitter-api-client#81]
Thank you for adding #77 . Can you clarify the correct usage though? 

The documentation makes it sounds like I simply change:

`scraper = Scraper(email, username, password)`

to 

`scraper = Scraper(cookies='twitter.cookies')`

But this results in an error:

```
[error] failed to update token at flow_username
'flow_token'
[error] failed to update token at flow_password
'flow_token'
[error] failed to update token at flow_duplication_check
'flow_token'
```

**Comment by enriquedecote** [comment]
Ah, found the solution on ticket #161 

Thanks for a great library!
