### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by lucasg1** [trevorhobenshield/twitter-api-client#84]
I've been using the search for about a month and it has been working fine until a couple days ago. I'm trying to search for anything and it's not working. My code:

```python
email, username, password = 'xxx@gmail.com', 'xxx', 'xxx'

search = Search(email, username, password, debug=1)

query = 'elon musk'
latest_results = search.run(
    query,
    limit=100,
    latest=True,  # get latest tweets only
    retries=3,
)
```

Result:

```terminal
[success] xxx login success
2023-06-21 10:09:00.120 [DEBUG] :: 'timeline'
2023-06-21 10:09:00.122 [DEBUG] :: No data for: elon musk, retrying in 1.98 seconds		
2023-06-21 10:09:02.278 [DEBUG] :: 'timeline'
2023-06-21 10:09:02.279 [DEBUG] :: No data for: elon musk, retrying in 2.17 seconds		
2023-06-21 10:09:04.620 [DEBUG] :: 'timeline'
2023-06-21 10:09:04.622 [DEBUG] :: No data for: elon musk, retrying in 4.99 seconds		
2023-06-21 10:09:09.776 [DEBUG] :: 'timeline'
2023-06-21 10:09:09.777 [DEBUG] :: Max retries exceeded
```

I tried:
- Without `latest`
- Other search queries
- My twitter account is OK, I checked that the search is working on the twitter website

**Comment by trevorhobenshield** [comment]
Thanks for this, good catch, they've just moved to a new endpoint. I'll let you know once I've added it.

**Comment by lucasg1** [comment]
Actually the endpoint is working. I tested with another library ([this one](https://github.com/n0madic/twitter-scraper)) and it's working. I also tested doing a plain HTTP request and it's also working:

![image](https://github.com/trevorhobenshield/twitter-api-client/assets/18517054/10125a2c-089e-4c3b-a943-6bc63de242ab)

Debugging a little bit I could figure out that the x-csrf-token is not being added to the request.

Response received from request (had to put a `print(data)` manually in the `get` function inside `search.py`):

```json
{'errors': [{'code': 353, 'message': 'This request requires a matching csrf cookie and header.'}]}
```

`print(get_headers(self.session))` inside process function in search.py:

Printed:
```
{'authorization': 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA', 'cookie': 'email=leandrofelix1961@gmail.com; flow_token=g;168735834796768345:-1687358348130:gGcdv0PLj0eeI6KCkePoHvu4:13; guest_token=1671528178785873921; password=rolhaGrande14*; username=leandro25632536; auth_token=429b264aabfba403178fe771be87b9f4edd63e0c; guest_id=v1%3A168735834796768345; guest_id_ads=v1%3A168735834796768345; guest_id_marketing=v1%3A168735834796768345; kdt=eld09G7hcVu8n9fATk6j6uLajVsUCUK0JOwos8gD; personalization_id="v1_baOpTDfb2xfE9YwVwLjAag=="; twid="u=1635271498473644032"', 'referer': 'https://twitter.com/', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36', 'x-csrf-token': '', 'x-guest-token': '1671528178785873921', 'x-twitter-active-user': 'yes', 'x-twitter-auth-type': 'OAuth2Session', 'x-twitter-client-language': 'en'}
```

As you can see, the x-csrf-token is empty: `'x-csrf-token': ''`

**Comment by lucasg1** [comment]
The problem is in the last commit of twitter/util.py, rolling back this specific file to previous version is working fine

Tested with version 0.9.7 and it is ok

**Comment by trevorhobenshield** [comment]
Upon further investigation I can't seem to replicate these errors anymore. It might have been a temporary issue on their end. If this happens again in the future I'll have a look at it. Recent example queries and output are below.

```python
from twitter.search import Search

search = Search(cookies='twitter.cookies',debug=1)

search.run(
    'shaktidb',
    'SAR OR "Synthetic-aperture radar" -tensorflow -tf -jax -trax',
    'vxunderground',
    limit=100,
    latest=True,
    retries=9,
)
```
![tmp](https://github.com/trevorhobenshield/twitter-api-client/assets/59624054/352aeed4-abd6-4a02-a109-d04f525be324)
