### ISSUE TITLE
Can I capture notifications?

### ISSUE THREAD

**Issue by itsurea** [trevorhobenshield/twitter-api-client#85]
I want to capture Twitter notifications in real time. Is it possible to implement this function?

**Comment by trevorhobenshield** [comment]
Hey thanks, great question. Just added it:

```python
account.notifications()
```

You'll just have to pick a polling frequency that fits within the bounds of their rate limits. Twitter polls your account at 30-second intervals, although the rate limit is currently 180 requests/15 minutes, so this would imply a minimum polling frequency of 5 seconds.
