### ISSUE TITLE
Error: Authorization: Denied by access control: unspecified reason

### ISSUE THREAD

**Issue by SD170** [trevorhobenshield/twitter-api-client#87]
Can you help me out. I'm getting this error while using the following internal graphql API. 

URL: `https://twitter.com/i/api/graphql/wjvx62Hye2dGVvnvVco0xA/Following`

```
{
  "errors": [
    {
      "message": "Authorization: Denied by access control: unspecified reason",
      "locations": [
        {
          "line": 7,
          "column": 11
        }
      ],
      "path": [
        "user",
        "result",
        "timeline",
        "timeline"
      ],
      "extensions": {
        "name": "AuthorizationError",
        "source": "Client",
        "code": 37,
        "kind": "Permissions",
        "tracing": {
          "trace_id": "b8ddd2308bb5eec0"
        }
      },
      "code": 37,
      "kind": "Permissions",
      "name": "AuthorizationError",
      "source": "Client",
      "tracing": {
        "trace_id": "b8ddd2308bb5eec0"
      }
    }
  ],
  "data": {
    "user": {
      "result": {
        "__typename": "User",
        "timeline": {}
      }
    }
  }
}
```

For headers I'm using this. Am I missing something??

```
Authorization:
		"Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA",
	    "x-guest-token": "1673608639570128896",
```

**Comment by trevorhobenshield** [comment]
Thanks for the question, it's a common error but unfortunately it's too generic to know exactly what's happening. I would first confirm that you can log-in using the web app, or try connecting to different regions over your VPN.

**Comment by SD170** [comment]
First of all thanks for the reply, I was trying to use the token Twitter uses internally. Is there any way I can keep using that, I actually have some constraints. 

Also, by `you can log-in using the web app` what do you mean actually?? You're talking about Oauth2 accessToken maybe. I've tried passing that as a Bearer also, in that case, it says I don't have API access. If you mean something else by that, can you please explain a little bit?


Also, the VPN thing I tried, no luck.
When I use 
`https://twitter.com/i/api/graphql/QvCV3AU7X1ZXr9JSrH9EOA/UserTweets`
this works perfectly, but the one that I mentioned doesn't. Can their internal policies for these APIs can't be different right??

Btw, thanks for the reply bro.

**Comment by trevorhobenshield** [comment]
Ah, okay so if the /UserTweets endpoint does return data for you but /Following does not then it's a simple case of not having the correct cookies set. /Following is an endpoint that requires authentication (either logging in using your email/password or using cookies from a previous session), whereas /UserTweets does not. So you'll just need to ensure you can successfully log-in on twitter.com, or the app. There might be some pending Arkose challenge or email confirmation task that is preventing you from signing in, in general.
