### ISSUE TITLE
How to only use auth_ Token for operation, instead of using ct0 and auth_ Token, can this be implemented?

### ISSUE THREAD

**Issue by wxtsky** [trevorhobenshield/twitter-api-client#89]
How to only use auth_ Token for operation, instead of usSome Twitter tool websites only use auth_ Token can perform a series of operations. How can I only use auth_ Token for operation, instead of using ct0 and auth_ Token, can this be implemented?ing ct0 and auth_ Token, can this be implemented?

**Comment by trevorhobenshield** [comment]
Nope, both csrf and auth tokens are required. You'll get a csrf-specific error if you don't include it, and without the auth token you'll likely be redirected to a login page
