### ISSUE TITLE
Encouraging not using `asyncio.run` in module

### ISSUE THREAD

**Issue by junyilou** [trevorhobenshield/twitter-api-client#91]
I am recently looking for a Python module to get tweet data without using the official API, and this module 100% makes the job done, really appreciate it. However, I do find some trouble implementing the module into my own project.

Since my main project is already async (i.e. using `async def` in most functions), I receive this RuntimeError when calling functions in my async event loop:

> RuntimeError('asyncio.run() cannot be called from a running event loop'

When digging through the source code, the problem is clear that (I think?) to eliminate the need to use `async`/`await` keyword outside, functions like `trends()`, `_run()` are not async functions, but they defines inner async function and uses `asyncio.run()` to wait for the result silently. I believe this behavior is highly unrecommended, and makes the module impossible to run inside another existing async event loop.

Even worse, sometimes `asyncio.run()` is called twice in the same function, like line 517 and line 522 in `scraper.py`:

https://github.com/trevorhobenshield/twitter-api-client/blob/55425b7181c1bd382c523a869dbcb622f1954f32/twitter/scraper.py#L509-L524

In Python [official documentation](https://docs.python.org/3/library/asyncio-runner.html) about asyncio runners:

> This function (asyncio.run()) always creates a new event loop and closes it at the end. It should be used as a main entry point for asyncio programs, and should ideally only be called once.

Practically, I never use `asyncio.run()` in modules. I will use them in scripts though (that runs and completes relatively quickly). I understand that this code works more like a script than a module (as by default it creates folders, files, and straightly prints out message), but it will be very helpful if it can be used as a module to call for multiple times. 

Even not, it is still recommended not to use `asyncio.run()` like this, you may create your own event loop and use lower-level API, or simply just keep the async functions **as async** and not try to force convert them into sync functions.

**Comment by trevorhobenshield** [comment]
I agree it's not ideal, however this package is designed such that it is usable for the largest number of people out of the box.

If this starts becoming a common issue for others in the future then I will look into factoring out the calls to run().

**Comment by junyilou** [comment]
https://github.com/junyilou/twitter-api-client

I forked the repo and remove all `asyncio.run()` function without affecting functionality. It is not perfect as well, but at least it now works in an async environment.

**Comment by 2-3-5-7** [comment]
You can use `run_in_executor` instead
```
    scraper = Scraper(cookies=get_cookies())
    loop = asyncio.get_running_loop()
    entries = await loop.run_in_executor(None, scraper.likes, [uid])
```

**Comment by junyilou** [comment]
> You can use `run_in_executor` instead
> 
> ```
>     scraper = Scraper(cookies=get_cookies())
>     loop = asyncio.get_running_loop()
>     entries = await loop.run_in_executor(None, scraper.likes, [uid])
> ```

If you want to use the `async` keyword you have to mark the function as async (i.e. `async def`), however, in that case, you don’t even need the loop, simply use `await <corountine>` will be enough, isn’t it

**Comment by BrokedTV** [comment]
> You can use `run_in_executor` instead
> 
> ```
>     scraper = Scraper(cookies=get_cookies())
>     loop = asyncio.get_running_loop()
>     entries = await loop.run_in_executor(None, scraper.likes, [uid])
> ```

Great workaround!

**Comment by koszzz** [comment]
> You can use `run_in_executor` instead
> 
> ```
>     scraper = Scraper(cookies=get_cookies())
>     loop = asyncio.get_running_loop()
>     entries = await loop.run_in_executor(None, scraper.likes, [uid])
> ```

SO NICE!!!
