### ISSUE TITLE
Rate limit exceeded.

### ISSUE THREAD

**Issue by triatic** [trevorhobenshield/twitter-api-client#92]
I'm seeing `Rate limit exceeded` for the first time. I pull a few feeds every 20 minutes for an RSS reader, but I've never seen this message before.

The message is: `[{"errors": [{"code": 88, "message": "Rate limit exceeded."}]}]`

Is anyone else getting this message for the first time? Have the rate limits been reduced?

**Comment by Kanozo** [comment]
The same thing happens to me, apparently due to the latest anti-scraping measures on Twitter.

https://twitter.com/elonmusk/status/1675187969420828672

**Comment by trevorhobenshield** [comment]
Yes, rate limits currently reduced as mentioned above by @Kanozo. You can set `debug=1` to view the current rate limit status of each endpoint when called.

Closing this as it's unrelated to the package/specific to Twitter servers.
