### ISSUE TITLE
search limit or another issue?

### ISSUE THREAD

**Issue by TMDR** [trevorhobenshield/twitter-api-client#93]
I slept last night and my bot was working, up until 6AM, when it crashed and it crashes every time I restart it.
![image](https://github.com/trevorhobenshield/twitter-api-client/assets/34814447/3de6d355-d265-4337-9b62-a605ef038f72)
when I tested it locally it just showed this, the response is empty (None) and it doesnt say anywhere that rate limit exceeded, did Twitter change something that can affect us, or is this just the rate limit?

**Comment by rikiraspoutine** [comment]
Same issue here ..

**Comment by triatic** [comment]
See #92

**Comment by TMDR** [comment]
hmm...so its a rate limit issue...disappointing, although scraping rather than searching seems to be working fine:
![image](https://github.com/trevorhobenshield/twitter-api-client/assets/34814447/27cbf738-c158-4812-ae9a-85c1c8b7fe7f)
anyway, Twitter really let me down on this one

**Comment by trevorhobenshield** [comment]
New search endpoint has been added and API has undergone changes. Queries are now represented as a list of dicts containing the query string and category. See [readme](https://github.com/trevorhobenshield/twitter-api-client#search) for details.

**Comment by TMDR** [comment]
thank you very much for this quick update!!
