### ISSUE TITLE
Search returns [[None]]

### ISSUE THREAD

**Issue by triatic** [trevorhobenshield/twitter-api-client#94]
I know we are all rate limited now. Just curious why Scraper returns:

```[{"errors": [{"code": 88, "message": "Rate limit exceeded."}]}]```

And Search returns, rather than the expected rate limit error:

```[[None]]```

**Comment by trevorhobenshield** [comment]
New search endpoint has been added and API has undergone changes. Queries are now represented as a list of dicts containing the query string and category. See [readme](https://github.com/trevorhobenshield/twitter-api-client#search) for details.

**Comment by triatic** [comment]
Thank you, will check it out now!
