### ISSUE TITLE
account.notifications help

### ISSUE THREAD

**Issue by itsurea** [trevorhobenshield/twitter-api-client#96]
Hello,

I have tried using the added notifications function. However, unless I check it on the Twitter web interface, the data will not be updated even if new notifications arrive.

**Comment by itsurea** [comment]
cursor add

**Comment by EinYs** [comment]
Hello could you describe a bit more how you solved the problem?

**Comment by itsurea** [comment]
> Hello could you describe a bit more how you solved the problem please?

This is an example code.

first = True
params = {
    "include_profile_interstitial_type": 1,
    "include_blocking": 1,
    "include_blocked_by": 1,
    "include_followed_by": 1,
    "include_want_retweets": 1,
    "include_mute_edge": 1,
    "include_can_dm": 1,
    "include_can_media_tag": 1,
    "include_ext_has_nft_avatar": 1,
    "include_ext_is_blue_verified": 1,
    "include_ext_verified_type": 1,
    "include_ext_profile_image_shape": 1,
    "skip_status": 1,
    "cards_platform": 'Web-12',
    "include_cards": 1,
    "include_ext_alt_text": 'true',
    "include_ext_limited_action_results": 'true',
    "include_quote_count": 'true',
    "include_reply_count": 1,
    "tweet_mode": 'extended',
    "include_ext_views": 'true',
    "include_entities": 'true',
    "include_user_entities": 'true',
    "include_ext_media_color": 'true',
    "include_ext_media_availability": 'true',
    "include_ext_sensitive_media_warning": 'true',
    "include_ext_trusted_friends_metadata": 'true',
    "send_error_codes": 'true',
    "simple_quoted_tweet": 'true',
    "count": 20,
    "requestContext": 'launch',
    "ext": 'mediaStats,highlightedLabel,hasNftAvatar,voiceInfo,birdwatchPivot,superFollowMetadata,unmentionInfo,editControl'
}

while(True):
  global params
  notifications = account.notifications(params)
  globalObjects = notifications['globalObjects']
  instructions = notifications['timeline']['instructions']

  for x in instructions:
    addEntries = x.get('addEntries')
    if addEntries:
    entries = addEntries['entries']
  for x in entries:
    entryId = x['entryId']
    find_cursor_top = entryId.find('cursor-top')
    if find_cursor_top != -1:
      content = x['content']
      operation = content.get('operation')
    if operation:
      cursor = operation['cursor']['value']

    if cursor:
      params['cursor'] = cursor

    if first == True:
      params['count'] = 40
      del params['requestContext']
      first = False
      time.sleep(7)
      continue
