### ISSUE TITLE
Limits to scrap

### ISSUE THREAD

**Issue by Kanozo** [trevorhobenshield/twitter-api-client#98]
It would be very useful if the _scraper.tweets_and_replies_  function could be passed parameters such as the limit of tweets or the maximum/minimum tweet id to reach.

**Comment by triatic** [comment]
Yes. The `since_id` query parameter of Twitter API V2 was very useful to limit the number of tweets pulled.

**Comment by trevorhobenshield** [comment]
Please see the readme, there is a limit parameter for almost all methods.

As for limiting by tweet ID, this falls out of scope for this package as it requires some form of post-processing to achieve the result. The goal of this package is to provide a simple low-level interface to the APIs.
