### ISSUE TITLE
Search - Remove hardcoded output directory, run function failes with OSError: [Errno 30] Read-only file system: 'data'

### ISSUE THREAD

**Issue by jhondoehop** [trevorhobenshield/twitter-api-client#99]
Hi, in this commit https://github.com/trevorhobenshield/twitter-api-client/commit/afba99f2eb3bc4060f282c777818f4de45fa2ecb#diff-70ddef683a2b1476cda1cc56ca33322376fb69744f5a3a530f10497f7f0fcd55 , you modified the run function to make a output dir `data/search_results` , in read-only systems (like AWS Lambda), its not running, can you please change it to back to a arg?

**Comment by trevorhobenshield** [comment]
Hi, thanks for the question. This has been fixed in latest version.

**Comment by jhondoehop** [comment]
Hi, thanks for the quick fix, could please do the same for the Scrapper also? https://github.com/trevorhobenshield/twitter-api-client/blob/8c12082ce7bec50e55b9915d85741e3d66adcfdd/twitter/scraper.py#L37

**Comment by trevorhobenshield** [comment]
fixed in `0.10.10`
